/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import  io.restassured.config.HttpClientConfig;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import  io.restassured.config.EncoderConfig;
import  io.restassured.http.ContentType;
import  org.hamcrest.Matchers;
import static org.hamcrest.Matchers.*;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-07-27T22:10:02.733949944-03:00[America/Argentina/Buenos_Aires]
 * <br>
*  The generated test suite contains 31 tests
 * <br>
*  Covered targets: 124
 * <br>
*  Used time: 0h 31m 33s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_successes_Test {

    
    private static String baseUrlOfSut = "https://api.twilio.com";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .httpClient(HttpClientConfig.httpClientConfig()
                .setParam("http.socket.timeout", 30000)
                .setParam("http.connection.timeout", 30000))
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .encoderConfig(EncoderConfig.encoderConfig().encodeContentTypeAs("application/octet-stream", ContentType.TEXT));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts.json
    */
    @Test(timeout = 60000)
    public void test_0_optionsOnAccounts_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{Sid}.json
    */
    @Test(timeout = 60000)
    public void test_1_optionsOnAccountReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC0Bdb3d0CAdFd8065C90ebC630E3ecC38.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Addresses.json
    */
    @Test(timeout = 60000)
    public void test_2_optionsOnAddresses_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACedF0aCd1eDC9d2a3BDD9eF1E0C9fFF5E/Addresses.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Applications.json
    */
    @Test(timeout = 60000)
    public void test_3_optionsOnApplications_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACE23564fC03F1D4FF37CDe1eF2Ca66661/Applications.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AuthorizedConnectApps.json
    */
    @Test(timeout = 60000)
    public void test_4_optionsOnAuthorizedConnectApps_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC2C1aEB19Cd22cBaa59AF0F46DFcD4b41/AuthorizedConnectApps.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers.json
    */
    @Test(timeout = 60000)
    public void test_5_optionsOnAvailablePhoneNumbers_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACEdB947A1804591f6350aAdD1EdbAda42/AvailablePhoneNumbers.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Balance.json
    */
    @Test(timeout = 60000)
    public void test_6_optionsOnBalance_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACAD6aEBadDe6d057CFB0993ccCDf1cfAF/Balance.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Calls.json
    */
    @Test(timeout = 60000)
    public void test_7_optionsOnCalls_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACcbEEAA37cb6aEA8f1eC3A90e72298B24/Calls.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Conferences.json
    */
    @Test(timeout = 60000)
    public void test_8_optionsOnConferences_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC690D74d735d9B34D3e3f68cB34CBDcc1/Conferences.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/ConnectApps.json
    */
    @Test(timeout = 60000)
    public void test_9_optionsOnConnectApps_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACefba32ab14950A7DE8bEA3a3B4aBF80c/ConnectApps.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Addresses/{Sid}.json
    */
    @Test(timeout = 60000)
    public void test_10_optionsOnAddressReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC24941Ced2461fb65D3a1Fb51Cb2d7BAc/Addresses/AD3BaCce1B03f6bdDb8AadDBA674f3DffA.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Applications/{Sid}.json
    */
    @Test(timeout = 60000)
    public void test_11_optionsOnApplicatReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC4F283630dc817BAa68DceBF8bFac143e/Applications/APafF0159b30a99a5fa7969acD04E8179D.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AuthorizedConnectApps/{ConnectAppSid}.json
    */
    @Test(timeout = 60000)
    public void test_12_optionsOnAuthorizedConnectAppReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC0FC8a5b52a9de3cacD175DA0E28dC283/AuthorizedConnectApps/CNd3874ab4Bd7BaB921184c4cD3F3C7b2b.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}.json
    */
    @Test(timeout = 60000)
    public void test_13_optionsOnAvailablePhoneNumbReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACeC90D0AeDDD16d913Cf8eACeDCba840c/AvailablePhoneNumbers/4Z5nfIasUrA8.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Calls/{Sid}.json
    */
    @Test(timeout = 60000)
    public void test_14_optionsOnCallReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACea6ff92dffC9fBEAe91b0824Be289C1A/Calls/CAbd6E86ca5A9c572E33ddeB1Bc2CeAc4B.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Conferences/{Sid}.json
    */
    @Test(timeout = 60000)
    public void test_15_optionsOnConferReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC0DfD45A1dB84cA82817cdB0AEE68d1cC/Conferences/CF8fa20a3b314bca55fbDbC8cb0a6deDe5.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/ConnectApps/{Sid}.json
    */
    @Test(timeout = 60000)
    public void test_16_optionsOnConnectAppReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACf5816389C4c548Ce5B45cFCcEAcA5EB0/ConnectApps/CNaf96ADBD2A3D325750FcfE41bEfc0A6D.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/Local.json
    */
    @Test(timeout = 60000)
    public void test_17_optionsOnLocal_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACD1D8acBc0A76EACDb93Dc4Cfcd83fc5E/AvailablePhoneNumbers/I5/Local.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/MachineToMachine.json
    */
    @Test(timeout = 60000)
    public void test_18_optionsOnMachineToMachine_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACEB4c73bed05DbEEd487Bfa2f7E20C09B/AvailablePhoneNumbers/kF2zVBVhSF8lpDO/MachineToMachine.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/Mobile.json
    */
    @Test(timeout = 60000)
    public void test_19_optionsOnMobile_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC312b4d2CcEafbcbFD11ea2F69AfDaa2d/AvailablePhoneNumbers/5C0LZ0sYIHjkwQis/Mobile.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/National.json
    */
    @Test(timeout = 60000)
    public void test_20_optionsOnNational_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC7b21EcaD6E3237c3349cCfcB9707DAaF/AvailablePhoneNumbers/Rs9haKVYkx/National.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/SharedCost.json
    */
    @Test(timeout = 60000)
    public void test_21_optionsOnSharedCost_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACafDc3Cbd7DaeE984cF7bDFd8734d3e20/AvailablePhoneNumbers/XDkjRgHlMcZ3vuN/SharedCost.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/TollFree.json
    */
    @Test(timeout = 60000)
    public void test_22_optionsOnTollFree_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC59f883ec0DAC6f6f87dcCfA5aE2Ae53d/AvailablePhoneNumbers/3HYqDXk/TollFree.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/Voip.json
    */
    @Test(timeout = 60000)
    public void test_23_optionsOnVoip_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC450BdD8C3f7a5A2b8dB9Fc5cae9ccC0C/AvailablePhoneNumbers/LnS_23Yiae3v_Lk/Voip.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Events.json
    */
    @Test(timeout = 60000)
    public void test_24_optionsOnEvents_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC1aD3847AAf2535B1177ee2aA2b580fbE/Calls/CA60a33c0eA1288fe6dbc9b8dE1e7BdE60/Events.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Notifications.json
    */
    @Test(timeout = 60000)
    public void test_25_optionsOnNotifications_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACA5cFdE6b3aDF3E3DfFE2796dc8675Aca/Calls/CA7CFC4dFBfcC7BD31AC1A0CD35eB0D37d/Notifications.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings.json
    */
    @Test(timeout = 60000)
    public void test_26_optionsOnCallRecordings_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACE6d555a4ADd6BEEd4dAcF1d8fB4cBfDe/Calls/CAcffAb5E1b1dA433CD802CBc7dCCeaDbF/Recordings.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Recordings.json
    */
    @Test(timeout = 60000)
    public void test_27_optionsOnConferRecordings_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/AC4adeD867Ac7ccae04Db6adcF6Ff12bAC/Conferences/CFe0Aec4FCFCac0CCeC0ED33Eaf761ddfa/Recordings.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Notifications/{Sid}.json
    */
    @Test(timeout = 60000)
    public void test_28_optionsOnNotifReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACDf4F40EaBe160DDdb90ae4bC14Cb84ec/Calls/CA4B3F6e5d2cFfC4ef0F1A72bB2E81AdDd/Notifications/NO9f8a83EdD3cEAbea647474bCd115EA3C.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Recordings/{Sid}.json
    */
    @Test(timeout = 60000)
    public void test_29_optionsOnCallRecordReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACd6c9DB4d6DcbE6FbC412a6a1fD5A1e7B/Calls/CA6Ee1e7A9CACdEC3b7EB6F60fe6EABE84/Recordings/REEF939AC4fb88bC1d0cd1BD2fa414eC57.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Conferences/{ConferenceSid}/Recordings/{Sid}.json
    */
    @Test(timeout = 60000)
    public void test_30_optionsOnConferRecordReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACEb31c8fE65888fCEF8dE2Fab078BD4A4/Conferences/CF8C3Beb745b4cDD361d4acBcB0fAEadb7/Recordings/RE5dC3CcC63D27a9cb33fdE86b89E63a9B.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
