/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import  io.restassured.config.HttpClientConfig;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import  io.restassured.config.EncoderConfig;
import  io.restassured.http.ContentType;
import  org.hamcrest.Matchers;
import static org.hamcrest.Matchers.*;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-07-28T22:13:58.311100303-03:00[America/Argentina/Buenos_Aires]
 * <br>
*  The generated test suite contains 1 tests
 * <br>
*  Covered targets: 3
 * <br>
*  Used time: 0h 30m 27s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_others_Test {

    
    private static String baseUrlOfSut = "https://api.themoviedb.org";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .httpClient(HttpClientConfig.httpClientConfig()
                .setParam("http.socket.timeout", 30000)
                .setParam("http.connection.timeout", 30000))
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .encoderConfig(EncoderConfig.encoderConfig().encodeContentTypeAs("application/octet-stream", ContentType.TEXT));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (401) GET:/3/authentication
    */
    @Test(timeout = 60000)
    public void test_0_getOnAuthenticationReturns401() throws Exception {
        
        given().accept("application/json")
                .get(baseUrlOfSut + "/3/authentication")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", isEmptyOrNullString())
                .contentType("application/json")
                .body("'status_code'", numberMatches(7))
                .body("'status_message'", containsString("Invalid API key: You must be granted a valid key."))
                .body("'success'", equalTo(false));
    }


}
