#!/usr/bin/env python

# LICENSE DISCLAIMER
# This file has been generated by EvoMaster.
# The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
# This generated software (i.e., the test suite in this file) can be freely used, modified, 
# and distributed as you see fit without any restrictions.
import json
import unittest
import requests
import time
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *
EM_HTTP_TIMEOUT_S = 30.0


#  This file was automatically generated by EvoMaster on 2026-08-12T20:23:29.192875165-03:00[America/Argentina/Buenos_Aires]
#  
#  The generated test suite contains 5 tests
#  
#  Covered targets: 19
#  
#  Used time: 0h 5m 27s
#  
#  Needed budget for current results: 84%
#  
#  This file contains test cases that are likely to indicate faults.
#  
class EvoMaster_faults_Test(unittest.TestCase):

    
    baseUrlOfSut = "https://voice.twilio.com"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (400) POST:/v3/Transcriptions
    # Found 1 potential fault of type-code 101
    # Using 3 examples:
    #   (-) BODY -> +15551234567
    #   (-) BODY -> 1
    #   (-) BODY -> Jane Doe
    @timeout_decorator.timeout(60)
    def test_0_post_on_Transcriptions_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.required Object has missing required properties (["status","title","type"])
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers["Idempotency-Key"] = "mcZCoeRYA"
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"transcriptionConfigurationId\" : \"voice_transcriptionconfiguration_aao29swdpn4ld888bmusq4je6w\", " + \
            " \"sourceId\" : \"RjIcOP6kiM7nb\", " + \
            " \"participants\" : [ { " + \
            " \"type\" : \"EVOMASTER\", " + \
            " \"address\" : \"\", " + \
            " \"audioChannelIndex\" : 2 " + \
            " }, { " + \
            " \"type\" : \"AI_AGENT\", " + \
            " \"address\" : \"+15551234567\", " + \
            " \"name\" : \"Jane Doe\", " + \
            " \"audioChannelIndex\" : 1 " + \
            " } ] " + \
            " } "
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/v3/Transcriptions",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["code"] == 20001
        assert res_0.json()["message"] == "request body field participants.null.type must be one of [CUSTOMER, HUMAN_AGENT, AI_AGENT]"
        assert res_0.json()["httpStatusCode"] == 400
        assert res_0.json()["userError"] == True
        assert res_0.json()["params"]["twilioErrorCodeUrl"] == "https://www.twilio.com/docs/errors/20001"
    
    
    # Calls:
    # (400) POST:/v3/Transcriptions
    # Found 1 potential fault of type-code 101
    # Using 2 examples:
    #   (-) BODY -> RExxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    #   (-) BODY -> voice_transcriptionconfiguration_5pe8jw3ahdmsh7zr06yh4d45x1
    @timeout_decorator.timeout(60)
    def test_1_post_on_Transcriptions_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.contentType.notAllowed Response Content-Type header 'application/problem+json' does not match any allowed types. Must be one of: [application/json].
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers["Idempotency-Key"] = "6gSW"
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"transcriptionConfigurationId\" : \"voice_transcriptionconfiguration_5pe8jw3ahdmsh7zr06yh4d45x1\", " + \
            " \"sourceId\" : \"RExxxxxxxxxxxxxxxxxxxxxxxxxxxxx\", " + \
            " \"participants\" : [ ] " + \
            " } "
        headers['Accept'] = "*/*"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/v3/Transcriptions",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/problem+json" in res_0.headers["content-type"]
        assert res_0.json()["title"] == "Bad Request"
        assert res_0.json()["status"] == 400
        assert res_0.json()["detail"] == "Failed to convert 'Idempotency-Key' with value: '6gSW'"
        assert res_0.json()["instance"] == "/v3/Transcriptions"
    
    
    # Calls:
    # (400) POST:/v3/Transcriptions
    # Found 1 potential fault of type-code 101
    # Using 2 examples:
    #   (-) BODY -> RExxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    #   (-) HEADER: Idempotency-Key -> 01926e40-a5e2-7000-8000-2b2c5a4e5d7b
    @timeout_decorator.timeout(60)
    def test_2_post_on_Transcriptions_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.required Object has missing required properties (["status","title","type"])
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers["Idempotency-Key"] = "01926e40-a5e2-7000-8000-2b2c5a4e5d7b"
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"transcriptionConfigurationId\" : \"voice_transcriptionconfiguration_95fuo3h59md0ausg4n7j7c0qu5\", " + \
            " \"inputSource\" : \"EVOMASTER\", " + \
            " \"sourceId\" : \"RExxxxxxxxxxxxxxxxxxxxxxxxxxxxx\", " + \
            " \"participants\" : [ { " + \
            " \"name\" : \"\", " + \
            " \"audioChannelIndex\" : 2 " + \
            " } ] " + \
            " } "
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/v3/Transcriptions",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["code"] == 400
        assert res_0.json()["message"] == "Request input may be invalid. Please check the format of your request and try again"
        assert res_0.json()["httpStatusCode"] == 400
        assert res_0.json()["userError"] == True
        assert res_0.json()["params"]["twilioErrorCodeUrl"] == "https://www.twilio.com/docs/errors/400"
    
    
    # Calls:
    # (401) POST:/v3/Transcriptions
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_3_post_on_Transcriptions_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.required Object has missing required properties (["status","title","type"])
        headers = {}
        headers["Idempotency-Key"] = "cY2BkCqybe9cc6cG"
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"transcriptionConfigurationId\" : \"voice_transcriptionconfiguration_8ikyif1hhdvufw98c1bg01ruvr\", " + \
            " \"sourceId\" : \"WPgaE6sNxv\", " + \
            " \"participants\" : [ ] " + \
            " } "
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/v3/Transcriptions",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "Basic realm=\"Twilio API\"" in res_0.headers["www-authenticate"]
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["code"] == 20003
        assert res_0.json()["message"] == "Authentication Error - No credentials provided"
        assert res_0.json()["httpStatusCode"] == 401
        assert res_0.json()["userError"] == True
        assert res_0.json()["params"]["twilioErrorCodeUrl"] == "https://www.twilio.com/docs/errors/20003"
    
    
    # Calls:
    # (401) GET:/v3/Transcriptions/{transcriptionId}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_4_get_on_Transcript_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.required Object has missing required properties (["status","title","type"])
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/v3/Transcriptions/voice_transcription_mPw2Y6h212qrIyoTGfr678y1GO",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "Basic realm=\"Twilio API\"" in res_0.headers["www-authenticate"]
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["code"] == 20003
        assert res_0.json()["message"] == "Authentication Error - No credentials provided"
        assert res_0.json()["httpStatusCode"] == 401
        assert res_0.json()["userError"] == True
        assert res_0.json()["params"]["twilioErrorCodeUrl"] == "https://www.twilio.com/docs/errors/20003"


if __name__ == '__main__':
    unittest.main()
