#!/usr/bin/env python

# LICENSE DISCLAIMER
# This file has been generated by EvoMaster.
# The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
# This generated software (i.e., the test suite in this file) can be freely used, modified, 
# and distributed as you see fit without any restrictions.
import json
import unittest
import requests
import time
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *
EM_HTTP_TIMEOUT_S = 30.0


#  This file was automatically generated by EvoMaster on 2026-08-12T20:23:29.220674994-03:00[America/Argentina/Buenos_Aires]
#  
#  The generated test suite contains 2 tests
#  
#  Covered targets: 8
#  
#  Used time: 0h 5m 27s
#  
#  Needed budget for current results: 84%
#  
#  This file contains test cases that represent successful calls.
#  
class EvoMaster_successes_Test(unittest.TestCase):

    
    baseUrlOfSut = "https://voice.twilio.com"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (200) OPTIONS:/v3/Transcriptions
    @timeout_decorator.timeout(60)
    def test_0_options_on_Transcriptions_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v3/Transcriptions",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert "text/plain" in res_0.headers["content-type"]
        assert "POST, OPTIONS" in res_0.text
    
    
    # Calls:
    # (200) OPTIONS:/v3/Transcriptions/{transcriptionId}
    @timeout_decorator.timeout(60)
    def test_1_options_on_Transcript_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v3/Transcriptions/voice_transcription_M9fksyIuBzqlGMNAVTyZ47ViPH",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert "text/plain" in res_0.headers["content-type"]
        assert "HEAD, GET, OPTIONS" in res_0.text


if __name__ == '__main__':
    unittest.main()
