#!/usr/bin/env python

# LICENSE DISCLAIMER
# This file has been generated by EvoMaster.
# The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
# This generated software (i.e., the test suite in this file) can be freely used, modified, 
# and distributed as you see fit without any restrictions.
import json
import unittest
import requests
import time
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *
EM_HTTP_TIMEOUT_S = 30.0


#  This file was automatically generated by EvoMaster on 2026-08-12T20:23:29.222416307-03:00[America/Argentina/Buenos_Aires]
#  
#  The generated test suite contains 2 tests
#  
#  Covered targets: 9
#  
#  Used time: 0h 5m 27s
#  
#  Needed budget for current results: 84%
#  
#  This file contains test cases that represent failed calls, but not indicative of faults.
#  
class EvoMaster_others_Test(unittest.TestCase):

    
    baseUrlOfSut = "https://voice.twilio.com"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (400) POST:/v3/Transcriptions
    # Using 3 examples:
    #   (-) BODY -> 1
    #   (-) BODY -> voice_transcriptionconfiguration_5pe8jw3ahdmsh7zr06yh4d45x1
    #   (-) HEADER: Idempotency-Key -> 01926e40-a5e2-7000-8000-2b2c5a4e5d7b
    @timeout_decorator.timeout(60)
    def test_0_post_on_Transcriptions_returns_400(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers["Idempotency-Key"] = "01926e40-a5e2-7000-8000-2b2c5a4e5d7b"
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"transcriptionConfigurationId\" : \"voice_transcriptionconfiguration_5pe8jw3ahdmsh7zr06yh4d45x1\", " + \
            " \"sourceId\" : \"5lm9Zhs\", " + \
            " \"participants\" : [ { " + \
            " \"type\" : \"CUSTOMER\", " + \
            " \"name\" : \"E_eDNoqeUi\", " + \
            " \"audioChannelIndex\" : 1 " + \
            " } ] " + \
            " } "
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/v3/Transcriptions",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["code"] == 1308
        assert res_0.json()["detail"] == "Request validation failed"
        assert len(res_0.json()["errors"]) == 1
        assert res_0.json()["errors"][0]["detail"] == "must match \"^RE[0-9a-zA-Z]+$\""
        assert res_0.json()["errors"][0]["pointer"] == "#/sourceId"
        assert res_0.json()["instance"] is None
        assert res_0.json()["status"] == 400
        assert res_0.json()["title"] == "Invalid Request Parameters"
        assert res_0.json()["type"] == "https://www.twilio.com/docs/api/errors/1308"
    
    
    # Calls:
    # (400) GET:/v3/Transcriptions/{transcriptionId}
    @timeout_decorator.timeout(60)
    def test_1_get_on_Transcript_returns_400(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/v3/Transcriptions/voice_transcription_OtSGifNNvylYzpZjP0ZEtPghkR",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["code"] == 1308
        assert res_0.json()["detail"] == "transcriptionId is invalid: voice_transcription_OtSGifNNvylYzpZjP0ZEtPghkR"
        assert res_0.json()["errors"] is None
        assert res_0.json()["instance"] is None
        assert res_0.json()["status"] == 400
        assert res_0.json()["title"] == "Invalid Request Parameters"
        assert res_0.json()["type"] == "https://www.twilio.com/docs/api/errors/1308"


if __name__ == '__main__':
    unittest.main()
