#!/usr/bin/env python

# LICENSE DISCLAIMER
# This file has been generated by EvoMaster.
# The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
# This generated software (i.e., the test suite in this file) can be freely used, modified, 
# and distributed as you see fit without any restrictions.
import json
import unittest
import requests
import time
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *
EM_HTTP_TIMEOUT_S = 30.0


#  This file was automatically generated by EvoMaster on 2026-08-13T08:55:47.148045261-03:00[America/Argentina/Buenos_Aires]
#  
#  The generated test suite contains 33 tests
#  
#  Covered targets: 119
#  
#  Used time: 0h 8m 54s
#  
#  Needed budget for current results: 100%
#  
#  This file contains test cases that are likely to indicate faults.
#  
class EvoMaster_faults_Test(unittest.TestCase):

    
    baseUrlOfSut = "https://api.openweathermap.org"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (401) GET:/geo/1.0/zip
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_0_get_on__1_0_zip_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/geo/1.0/zip?appid=%3CYOUR_KEY%3E",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/geo/1.0/reverse
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_1_get_on_reverse_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/geo/1.0/reverse?" + 
                    "appid=Y8CK_6Fw&" + 
                    "lat=20.369041&" + 
                    "lon=16.374228&" + 
                    "limit=1",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/geo/1.0/reverse
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_2_get_on_reverse_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/geo/1.0/reverse?" + 
                    "appid=9AFi0Y&" + 
                    "lon=18.632647",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/geo/1.0/reverse
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_3_get_on_reverse_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/geo/1.0/reverse?" + 
                    "appid=qxrX&" + 
                    "lat=26.548092&" + 
                    "lon=49.00924",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/geo/1.0/direct
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_4_get_on_direct_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/geo/1.0/direct?" + 
                    "appid=X3rjBR&" + 
                    "limit=5",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_5_get_on__2_5_air_pollution_with_queryParams_negative_lat_and_negative_lon_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution?" + 
                    "appid=11ztJpGyrN1gf&" + 
                    "lat=-88.57431&" + 
                    "lon=-147.28502",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_6_get_on__2_5_air_pollution_with_queryParams_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution?" + 
                    "appid=QUunwaaN6V&" + 
                    "lon=63.497864",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_7_get_on__2_5_air_pollution_with_queryParams_negative_lat_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution?" + 
                    "appid=jwG_L_m&" + 
                    "lat=-9.472055&" + 
                    "lon=35.855896",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/forecast
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_8_get_on__2_5_forecast_with_queryParams_negative_lat_and_negative_lon_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/forecast?" + 
                    "appid=JfSDeEf&" + 
                    "q=cMHcPpnL&" + 
                    "lat=-13.209765&" + 
                    "lon=-122.24279&" + 
                    "zip=FFrSx_lA&" + 
                    "units=imperial&" + 
                    "cnt=30",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/forecast
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_9_get_on__2_5_forecast_with_queryParams_negative_lon_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/forecast?" + 
                    "appid=Z2FQRKvleW4F&" + 
                    "id=19&" + 
                    "lon=-4.8812966&" + 
                    "zip=N49Eh_egM9xTT&" + 
                    "units=standard&" + 
                    "cnt=24",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/forecast
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_10_get_on_forecast_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/forecast?" + 
                    "appid=bI6oLjnEPwJj5Fmc&" + 
                    "q=D&" + 
                    "lat=54.996815&" + 
                    "units=imperial&" + 
                    "cnt=19",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/weather
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_11_get_on_weather_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/weather?" + 
                    "appid=I&" + 
                    "id=949&" + 
                    "lat=-58.546402&" + 
                    "lon=-87.57031&" + 
                    "zip=32j&" + 
                    "units=imperial&" + 
                    "lang=E",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/forecast
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_12_get_on_forecast_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/forecast?" + 
                    "appid=oXh8M&" + 
                    "lat=27.73821&" + 
                    "cnt=1",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/geo/1.0/direct
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_13_get_on_direct_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/geo/1.0/direct?" + 
                    "appid=pQH9_tvjs&" + 
                    "q=RmIeDO0An2E3MryS",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/weather
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_14_get_on_weather_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/weather?" + 
                    "appid=mZcjRQ2cDh&" + 
                    "id=217&" + 
                    "lat=25.825996&" + 
                    "lon=143.09384&" + 
                    "zip=D5OrZVYxebIa5&" + 
                    "units=imperial&" + 
                    "lang=JY",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/geo/1.0/zip
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_15_get_on__1_0_zip_with_queryParams_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/geo/1.0/zip?" + 
                    "appid=uui&" + 
                    "zip=Ajf0a",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/weather
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_16_get_on_weather_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/weather?" + 
                    "appid=PMsa2X_yZ2BVTv&" + 
                    "id=412&" + 
                    "lat=33.527214",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/geo/1.0/reverse
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_17_get_on_reverse_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/geo/1.0/reverse?" + 
                    "appid=lDfoL2d0q8t0&" + 
                    "limit=3",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/forecast
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_18_get_on_forecast_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/forecast?" + 
                    "appid=8RVt4Og2APA1WN&" + 
                    "id=435&" + 
                    "zip=vR&" + 
                    "lang=7wmvsrcrWAcxOgr&" + 
                    "cnt=32",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/forecast
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_19_get_on_forecast_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/forecast?" + 
                    "appid=kn&" + 
                    "id=626&" + 
                    "lang=3",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/weather
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_20_get_on_weather_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/weather?" + 
                    "appid=R&" + 
                    "id=721&" + 
                    "zip=_TFRGFBg&" + 
                    "lang=Yzke2Ft8y",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/weather
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_21_get_on_weather_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/weather?" + 
                    "appid=kwOHRBc4lQwFXsJ&" + 
                    "lat=80.48615&" + 
                    "lon=155.09825&" + 
                    "zip=kPxW7Fwc&" + 
                    "units=standard&" + 
                    "lang=l9ri1ZrUfvPlPOyA",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/weather
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_22_get_on_weather_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/weather?" + 
                    "appid=ZV1&" + 
                    "q=7ZsqlOqTXMQ&" + 
                    "lat=-37.92603&" + 
                    "lon=-61.874077&" + 
                    "zip=G9f&" + 
                    "lang=KXfvAgqbJZmMpWO",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_23_get_on__2_5_air_pollution_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution?appid=Cq",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution/history
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_24_get_on_history_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution/history?" + 
                    "appid=ku9y2X62q&" + 
                    "lat=-87.317276&" + 
                    "lon=99.416046&" + 
                    "start=435&" + 
                    "end=798",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution/history
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_25_get_on_air_pollution_history_with_queryParams_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution/history?" + 
                    "appid=l1v&" + 
                    "lon=11.4083395&" + 
                    "start=237&" + 
                    "end=96",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution/forecast
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_26_get_on_air_pollution_forecast_with_queryParams_negative_lon_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution/forecast?" + 
                    "appid=EAaJz3twiH2pq&" + 
                    "lat=81.26871&" + 
                    "lon=-29.96992",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution/forecast
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_27_get_on_forecast_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution/forecast?" + 
                    "appid=GQ&" + 
                    "lon=5.543033",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution/forecast
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_28_get_on_forecast_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution/forecast?" + 
                    "appid=vksN7mD5&" + 
                    "lat=86.04788&" + 
                    "lon=44.53994",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution/forecast
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_29_get_on_forecast_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution/forecast?" + 
                    "appid=N5RGhu&" + 
                    "lat=46.51619",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution/history
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_30_get_on_history_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution/history?" + 
                    "appid=zOAz_OV&" + 
                    "lat=-38.394844&" + 
                    "start=340&" + 
                    "end=196",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution/history
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_31_get_on_air_pollution_history_with_queryParams_negative_end_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution/history?" + 
                    "appid=lUktG3pB&" + 
                    "start=367&" + 
                    "end=-264082779",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) GET:/data/2.5/air_pollution/forecast
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_32_get_on_air_pollution_forecast_with_queryParams_negative_lat_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        headers = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/data/2.5/air_pollution/forecast?" + 
                    "appid=mjzx&" + 
                    "lat=-11.452421&" + 
                    "lon=118.21994",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."


if __name__ == '__main__':
    unittest.main()
