#!/usr/bin/env python

# LICENSE DISCLAIMER
# This file has been generated by EvoMaster.
# The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
# This generated software (i.e., the test suite in this file) can be freely used, modified, 
# and distributed as you see fit without any restrictions.
import json
import unittest
import requests
import time
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *
EM_HTTP_TIMEOUT_S = 30.0


#  This file was automatically generated by EvoMaster on 2026-08-13T08:55:47.190467774-03:00[America/Argentina/Buenos_Aires]
#  
#  The generated test suite contains 6 tests
#  
#  Covered targets: 12
#  
#  Used time: 0h 8m 54s
#  
#  Needed budget for current results: 100%
#  
#  This file contains test cases that represent failed calls, but not indicative of faults.
#  
class EvoMaster_others_Test(unittest.TestCase):

    
    baseUrlOfSut = "https://api.openweathermap.org"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (401) OPTIONS:/data/2.5/weather
    @timeout_decorator.timeout(60)
    def test_0_options_on_weather_returns_401(self):
        
        headers = {}
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/data/2.5/weather",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) OPTIONS:/data/2.5/forecast
    @timeout_decorator.timeout(60)
    def test_1_options_on__2_5_forecast_returns_401(self):
        
        headers = {}
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/data/2.5/forecast",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) OPTIONS:/data/2.5/air_pollution
    @timeout_decorator.timeout(60)
    def test_2_options_on_air_pollution_returns_401(self):
        
        headers = {}
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/data/2.5/air_pollution",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) OPTIONS:/geo/1.0/direct
    @timeout_decorator.timeout(60)
    def test_3_options_on_direct_returns_401(self):
        
        headers = {}
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/geo/1.0/direct",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) OPTIONS:/data/2.5/air_pollution/forecast
    @timeout_decorator.timeout(60)
    def test_4_options_on_air_pollution_forecast_returns_401(self):
        
        headers = {}
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/data/2.5/air_pollution/forecast",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."
    
    
    # Calls:
    # (401) OPTIONS:/data/2.5/air_pollution/history
    @timeout_decorator.timeout(60)
    def test_5_options_on_history_returns_401(self):
        
        headers = {}
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/data/2.5/air_pollution/history",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["cod"] == 401
        assert res_0.json()["message"] == "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."


if __name__ == '__main__':
    unittest.main()
