/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import  io.restassured.config.HttpClientConfig;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import  io.restassured.config.EncoderConfig;
import  io.restassured.http.ContentType;
import  org.hamcrest.Matchers;
import static org.hamcrest.Matchers.*;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-07-27T21:20:58.693999889-03:00[America/Argentina/Buenos_Aires]
 * <br>
*  The generated test suite contains 18 tests
 * <br>
*  Covered targets: 60
 * <br>
*  Used time: 0h 3m 28s
 * <br>
*  Needed budget for current results: 95%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_others_Test {

    
    private static String baseUrlOfSut = "https://api-m.sandbox.paypal.com";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .httpClient(HttpClientConfig.httpClientConfig()
                .setParam("http.socket.timeout", 30000)
                .setParam("http.connection.timeout", 30000))
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .encoderConfig(EncoderConfig.encoderConfig().encodeContentTypeAs("application/octet-stream", ContentType.TEXT));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (400) POST:/v2/checkout/orders
    * Using 2 examples:
    *   (orders_create_create_orders_with_shipping_type_pickup_in_store) BODY -> {"intent":"AUTHORIZE", "purchase_units":[{"reference_id":"PUHF","amount":{"currency_code":"USD","value":"50.00"},"payee":{"email_address":"merchant@example.com"},"shipping":{"address":{"address_line_1":"123 Townsend St","address_line_2":"Floor 6","admin_area_2":"San Francisco","admin_area_1":"CA","postal_code":"94107","country_code":"US"},"type":"PICKUP_IN_STORE"}}], "application_context":{"locale":{
                    "mL6iICz6Hwk3F":""
                    ,
                    "zvqT07T_yrYUq9":"1ZV93jh9Fx0xNN"
                    ,
                    "54qiXXpU":"ubtmnjgkhr"
                    }, "shipping_preference":"NO_SHIPPING", "return_url":"https://example.com/returnUrl", "cancel_url":"https://example.com/cancelUrl", "stored_payment_source":{"payment_initiator":"EVOMASTER", "payment_type":"EVOMASTER", "usage":"DERIVED"}}}
    *   (orders_create_create_orders_with_shipping_type_pickup_in_store) HEADER: Prefer -> return=representation
    */
    @Test(timeout = 60000)
    public void test_0_postOnOrdersReturns400() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .header("PayPal-Client-Metadata-Id", "9")
                .header("Prefer", "return=representation")
                .contentType("application/json")
                .body(" { " + 
                    " \"intent\" : \"AUTHORIZE\", " + 
                    " \"purchase_units\" : [ { " + 
                    " \"reference_id\" : \"PUHF\", " + 
                    " \"amount\" : { " + 
                    " \"currency_code\" : \"USD\", " + 
                    " \"value\" : \"50.00\" " + 
                    " }, " + 
                    " \"payee\" : { " + 
                    " \"email_address\" : \"merchant@example.com\" " + 
                    " }, " + 
                    " \"shipping\" : { " + 
                    " \"address\" : { " + 
                    " \"address_line_1\" : \"123 Townsend St\", " + 
                    " \"address_line_2\" : \"Floor 6\", " + 
                    " \"admin_area_2\" : \"San Francisco\", " + 
                    " \"admin_area_1\" : \"CA\", " + 
                    " \"postal_code\" : \"94107\", " + 
                    " \"country_code\" : \"US\" " + 
                    " }, " + 
                    " \"type\" : \"PICKUP_IN_STORE\" " + 
                    " } " + 
                    " } ], " + 
                    " \"application_context\" : { " + 
                    " \"locale\" : { " + 
                    " \"mL6iICz6Hwk3F\" : \"\", " + 
                    " \"zvqT07T_yrYUq9\" : \"1ZV93jh9Fx0xNN\", " + 
                    " \"54qiXXpU\" : \"ubtmnjgkhr\" " + 
                    " }, " + 
                    " \"shipping_preference\" : \"NO_SHIPPING\", " + 
                    " \"return_url\" : \"https://example.com/returnUrl\", " + 
                    " \"cancel_url\" : \"https://example.com/cancelUrl\", " + 
                    " \"stored_payment_source\" : { " + 
                    " \"payment_initiator\" : \"EVOMASTER\", " + 
                    " \"payment_type\" : \"EVOMASTER\", " + 
                    " \"usage\" : \"DERIVED\" " + 
                    " } " + 
                    " } " + 
                    " } ")
                .post(baseUrlOfSut + "/v2/checkout/orders")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("INVALID_REQUEST"))
                .body("'message'", containsString("Request is not well-formed, syntactically incorrect, or violates schema."))
                .body("'debug_id'", containsString("f256686c5fdab"))
                .body("'details'.size()", equalTo(1))
                .body("'details'[0].'field'", containsString("/application_context/locale"))
                .body("'details'[0].'location'", containsString("body"))
                .body("'details'[0].'issue'", containsString("MALFORMED_REQUEST_JSON"))
                .body("'details'[0].'description'", containsString("The request JSON is not well formed."))
                .body("'links'.size()", equalTo(1))
                .body("'links'[0].'href'", containsString("https://developer.paypal.com/docs/api/orders/v2/#error-MALFORMED_REQUEST_JSON"))
                .body("'links'[0].'rel'", containsString("information_link"))
                .body("'links'[0].'encType'", containsString("application/json"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/checkout/orders
    * Using 3 examples:
    *   (00_orders_create) BODY -> {"intent":"EVOMASTER", "payer":{"payer_id":{
                    "OZ":"ewKkaUxStV6n"
                    ,
                    "r6AlU11ZJu9oeK":"EH5t"
                    ,
                    "VVi2OH":"aMWwuk"
                    ,
                    "Qy0o":"1N3u6wMiwoNYHf6"
                    }, "birth_date":{
                    "qcpJvYpi3M":"8d1UxssdQFz"
                    }, "tax_info":{"tax_id":"Y", "tax_id_type":"EVOMASTER"}, "address":{"address_line_2":"ᾘ", "admin_area_4":"", "admin_area_2":"訂", "admin_area_1":"抒혂", "postal_code":"", "country_code":"C2"}}, "purchase_units":[{"invoice_id":"90210","amount":{"currency_code":"USD","value":"230.00","breakdown":{"item_total":{"currency_code":"USD","value":"220.00"},"shipping":{"currency_code":"USD","value":"10.00"}}},"items":[{"name":"T-Shirt","description":"Super Fresh Shirt","unit_amount":{"currency_code":"USD","value":"20.00"},"quantity":"1","category":"PHYSICAL_GOODS","sku":"sku01","image_url":"https://example.com/static/images/items/1/tshirt_green.jpg","url":"https://example.com/url-to-the-item-being-purchased-1","upc":{"type":"UPC-A","code":"123456789012"}},{"name":"Shoes","description":"Running, Size 10.5","sku":"sku02","unit_amount":{"currency_code":"USD","value":"100.00"},"quantity":"2","category":"PHYSICAL_GOODS","image_url":"https://example.com/static/images/items/1/shoes_running.jpg","url":"https://example.com/url-to-the-item-being-purchased-2","upc":{"type":"UPC-A","code":"987654321012"}}]}], "payment_source":{"token":{"id":"GL", "type":"BILLING_AGREEMENT"}, "paypal":{"vault_id":{
                    "vK1emXHuPAh4tBJ3":"QWSx99uepgje"
                    }, "email_address":{
                    "jRSD5SlYDV":"i7xuz_"
                    ,
                    "6M88":"DPz9dk8rl"
                    ,
                    "X08n9dSrKVeG":"O_TkK70e9Pzyf26"
                    ,
                    "4T7FOKYVsUH6H":"C"
                    }, "birth_date":{
                    "K":"Nz"
                    ,
                    "p":"gX"
                    ,
                    "8dErevdzb":"eE7o"
                    }, "address":{"address_line_1":"", "address_line_2":"ꜚꄍ", "address_line_3":"", "admin_area_3":"➁", "admin_area_2":"䇝鿹", "country_code":"C2", "address_details":{"street_number":"ᇯ", "street_type":"鷀", "delivery_service":"缕"}}, "attributes":{"vault":{"description":"䄕枣", "usage_pattern":"IMMEDIATE", "usage_type":"MERCHANT", "customer_type":"CONSUMER"}}, "experience_context":{"brand_name":"塓&", "shipping_preference":"GET_FROM_FILE", "return_url":"https://example.com/returnUrl", "cancel_url":"https://example.com/cancelUrl", "app_switch_context":{}, "landing_page":"LOGIN", "user_action":"PAY_NOW", "payment_method_preference":"IMMEDIATE_PAYMENT_REQUIRED", "order_update_callback_config":{"callback_events":["SHIPPING_OPTIONS", "EVOMASTER", "SHIPPING_ADDRESS"], "callback_url":"GWjn1xFCQMLl"}}, "stored_credential":{"payment_initiator":"CUSTOMER", "charge_pattern":{
                    "xUPiaxrN5q":"YZABVru7_z"
                    }, "usage_pattern":"INSTALLMENT_PREPAID", "usage":"FIRST"}}, "eps":{"name":{}, "country_code":{
                    "MM4qxWE67":"S2XL4cg5U"
                    ,
                    "9Uza50h":"KU4xxKQ7"
                    ,
                    "dX4cvoiV6F_":"OfRnoE7Q8Kjf"
                    ,
                    "TIF":"hjU0KZ0"
                    }, "experience_context":{"brand_name":"跎", "locale":{}, "shipping_preference":"NO_SHIPPING"}}, "giropay":{"name":{
                    "PbMy2bXE4NXM":"zGg_2"
                    ,
                    "2L":"lmWM61yNMK"
                    ,
                    "Xwzo":"Jhh4vq"
                    ,
                    "fVpMuLj":"G"
                    }, "country_code":{
                    "mY4kSHs0EO":"YqyN0"
                    }}, "mybank":{"name":{}, "country_code":{
                    "JN8":"RvNhgMoxYfe"
                    ,
                    "Afgm1UO2o":"Bw9lk3JVDrNQPLM"
                    }, "experience_context":{"locale":{
                    "Qxv1Plkcv":"m2vWMt00o"
                    ,
                    "UZb":"slH9ss_Kx3VZv"
                    ,
                    "nej89HE1AC":"inZdVn1TXIE"
                    ,
                    "ovYDfcXMGkm":"pGmqFXnI1gU"
                    ,
                    "2rgxhG3lgEDei1":"AX"
                    }, "shipping_preference":"GET_FROM_FILE", "cancel_url":"https://www.example.com/cancelURL"}}, "p24":{"name":{
                    "z":"kgNO3gXe"
                    ,
                    "o6":"r7PcbeMw3haU"
                    ,
                    "8LeVIaF5ix":"2Ao7"
                    }, "email":{
                    "H":"A4Wut"
                    ,
                    "PmXGC82":"lytITgCM9xm2Yk"
                    }, "country_code":{
                    "koex20nRhL3xzMq":"lva"
                    }, "experience_context":{"return_url":"https://example.com/returnUrl", "cancel_url":"https://www.example.com/cancelURL"}}, "google_pay":{"email_address":{
                    "COtSj6KQrwE7":"4T7bZ8lQA8iDI5"
                    ,
                    "FuKMnq7fEO":"HtccEJOrTmfUv"
                    }, "decrypted_token":{"message_expiration":"1635269042807", "payment_method":"CARD", "card":{"name":"", "number":"2266766152400", "last_digits":"0119", "type":{
                    "7pna8R9W7lEz_":"c145UzvweP"
                    }, "brand":{
                    "i":"QkhMKKjt"
                    ,
                    "KgaQld4bxJDFlEY":"vEpNDRLEl7Vcben"
                    ,
                    "z2lJH0HkPRS1fapH":"eE"
                    }}, "authentication_method":"CRYPTOGRAM_3DS", "eci_indicator":"佼"}}, "venmo":{"vault_id":{
                    "P0tW":"HWSbnQnTPP5x10"
                    ,
                    "hbYlGVgMN_QVT":"uvNKx6h7Kq8SJ"
                    ,
                    "idT":"zkCsZ0x8ar3D"
                    ,
                    "WXH75dKasyg9aaU":""
                    ,
                    "8S":"yX_9WcrgevB5quq"
                    }, "attributes":{"vault":{"description":"", "customer_type":"CONSUMER", "permit_multiple_payment_tokens":true}}}}}
    *   (00_orders_create) HEADER: PayPal-Request-Id -> 7b92603e-77ed-4896-8e78-5dea2050476a
    *   (auth_assertion) HEADER: PayPal-Auth-Assertion -> eyJhbGciOiJub25lIn0.eyJlbWFpbCI6Im15QGVtYWlsLmNvbSJ9
    */
    @Test(timeout = 60000)
    public void test_1_postOnOrdersReturns400() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .header("PayPal-Request-Id", "7b92603e-77ed-4896-8e78-5dea2050476a")
                .header("PayPal-Partner-Attribution-Id", "位")
                .header("Prefer", "e")
                .contentType("application/json")
                .body(" { " + 
                    " \"intent\" : \"EVOMASTER\", " + 
                    " \"payer\" : { " + 
                    " \"payer_id\" : { " + 
                    " \"OZ\" : \"ewKkaUxStV6n\", " + 
                    " \"r6AlU11ZJu9oeK\" : \"EH5t\", " + 
                    " \"VVi2OH\" : \"aMWwuk\", " + 
                    " \"Qy0o\" : \"1N3u6wMiwoNYHf6\" " + 
                    " }, " + 
                    " \"birth_date\" : { " + 
                    " \"qcpJvYpi3M\" : \"8d1UxssdQFz\" " + 
                    " }, " + 
                    " \"tax_info\" : { " + 
                    " \"tax_id\" : \"Y\", " + 
                    " \"tax_id_type\" : \"EVOMASTER\" " + 
                    " }, " + 
                    " \"address\" : { " + 
                    " \"address_line_2\" : \"ᾘ\", " + 
                    " \"admin_area_4\" : \"\", " + 
                    " \"admin_area_2\" : \"訂\", " + 
                    " \"admin_area_1\" : \"抒혂\", " + 
                    " \"postal_code\" : \"\", " + 
                    " \"country_code\" : \"C2\" " + 
                    " } " + 
                    " }, " + 
                    " \"purchase_units\" : [ { " + 
                    " \"invoice_id\" : \"90210\", " + 
                    " \"amount\" : { " + 
                    " \"currency_code\" : \"USD\", " + 
                    " \"value\" : \"230.00\", " + 
                    " \"breakdown\" : { " + 
                    " \"item_total\" : { " + 
                    " \"currency_code\" : \"USD\", " + 
                    " \"value\" : \"220.00\" " + 
                    " }, " + 
                    " \"shipping\" : { " + 
                    " \"currency_code\" : \"USD\", " + 
                    " \"value\" : \"10.00\" " + 
                    " } " + 
                    " } " + 
                    " }, " + 
                    " \"items\" : [ { " + 
                    " \"name\" : \"T-Shirt\", " + 
                    " \"description\" : \"Super Fresh Shirt\", " + 
                    " \"unit_amount\" : { " + 
                    " \"currency_code\" : \"USD\", " + 
                    " \"value\" : \"20.00\" " + 
                    " }, " + 
                    " \"quantity\" : \"1\", " + 
                    " \"category\" : \"PHYSICAL_GOODS\", " + 
                    " \"sku\" : \"sku01\", " + 
                    " \"image_url\" : \"https://example.com/static/images/items/1/tshirt_green.jpg\", " + 
                    " \"url\" : \"https://example.com/url-to-the-item-being-purchased-1\", " + 
                    " \"upc\" : { " + 
                    " \"type\" : \"UPC-A\", " + 
                    " \"code\" : \"123456789012\" " + 
                    " } " + 
                    " }, { " + 
                    " \"name\" : \"Shoes\", " + 
                    " \"description\" : \"Running, Size 10.5\", " + 
                    " \"sku\" : \"sku02\", " + 
                    " \"unit_amount\" : { " + 
                    " \"currency_code\" : \"USD\", " + 
                    " \"value\" : \"100.00\" " + 
                    " }, " + 
                    " \"quantity\" : \"2\", " + 
                    " \"category\" : \"PHYSICAL_GOODS\", " + 
                    " \"image_url\" : \"https://example.com/static/images/items/1/shoes_running.jpg\", " + 
                    " \"url\" : \"https://example.com/url-to-the-item-being-purchased-2\", " + 
                    " \"upc\" : { " + 
                    " \"type\" : \"UPC-A\", " + 
                    " \"code\" : \"987654321012\" " + 
                    " } " + 
                    " } ] " + 
                    " } ], " + 
                    " \"payment_source\" : { " + 
                    " \"token\" : { " + 
                    " \"id\" : \"GL\", " + 
                    " \"type\" : \"BILLING_AGREEMENT\" " + 
                    " }, " + 
                    " \"paypal\" : { " + 
                    " \"vault_id\" : { " + 
                    " \"vK1emXHuPAh4tBJ3\" : \"QWSx99uepgje\" " + 
                    " }, " + 
                    " \"email_address\" : { " + 
                    " \"jRSD5SlYDV\" : \"i7xuz_\", " + 
                    " \"6M88\" : \"DPz9dk8rl\", " + 
                    " \"X08n9dSrKVeG\" : \"O_TkK70e9Pzyf26\", " + 
                    " \"4T7FOKYVsUH6H\" : \"C\" " + 
                    " }, " + 
                    " \"birth_date\" : { " + 
                    " \"K\" : \"Nz\", " + 
                    " \"p\" : \"gX\", " + 
                    " \"8dErevdzb\" : \"eE7o\" " + 
                    " }, " + 
                    " \"address\" : { " + 
                    " \"address_line_1\" : \"\", " + 
                    " \"address_line_2\" : \"ꜚꄍ\", " + 
                    " \"address_line_3\" : \"\", " + 
                    " \"admin_area_3\" : \"➁\", " + 
                    " \"admin_area_2\" : \"䇝鿹\", " + 
                    " \"country_code\" : \"C2\", " + 
                    " \"address_details\" : { " + 
                    " \"street_number\" : \"ᇯ\", " + 
                    " \"street_type\" : \"鷀\", " + 
                    " \"delivery_service\" : \"缕\" " + 
                    " } " + 
                    " }, " + 
                    " \"attributes\" : { " + 
                    " \"vault\" : { " + 
                    " \"description\" : \"䄕枣\", " + 
                    " \"usage_pattern\" : \"IMMEDIATE\", " + 
                    " \"usage_type\" : \"MERCHANT\", " + 
                    " \"customer_type\" : \"CONSUMER\" " + 
                    " } " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"brand_name\" : \"塓&\", " + 
                    " \"shipping_preference\" : \"GET_FROM_FILE\", " + 
                    " \"return_url\" : \"https://example.com/returnUrl\", " + 
                    " \"cancel_url\" : \"https://example.com/cancelUrl\", " + 
                    " \"app_switch_context\" : { }, " + 
                    " \"landing_page\" : \"LOGIN\", " + 
                    " \"user_action\" : \"PAY_NOW\", " + 
                    " \"payment_method_preference\" : \"IMMEDIATE_PAYMENT_REQUIRED\", " + 
                    " \"order_update_callback_config\" : { " + 
                    " \"callback_events\" : [ \"SHIPPING_OPTIONS\", \"EVOMASTER\", \"SHIPPING_ADDRESS\" ], " + 
                    " \"callback_url\" : \"GWjn1xFCQMLl\" " + 
                    " } " + 
                    " }, " + 
                    " \"stored_credential\" : { " + 
                    " \"payment_initiator\" : \"CUSTOMER\", " + 
                    " \"charge_pattern\" : { " + 
                    " \"xUPiaxrN5q\" : \"YZABVru7_z\" " + 
                    " }, " + 
                    " \"usage_pattern\" : \"INSTALLMENT_PREPAID\", " + 
                    " \"usage\" : \"FIRST\" " + 
                    " } " + 
                    " }, " + 
                    " \"eps\" : { " + 
                    " \"name\" : { }, " + 
                    " \"country_code\" : { " + 
                    " \"MM4qxWE67\" : \"S2XL4cg5U\", " + 
                    " \"9Uza50h\" : \"KU4xxKQ7\", " + 
                    " \"dX4cvoiV6F_\" : \"OfRnoE7Q8Kjf\", " + 
                    " \"TIF\" : \"hjU0KZ0\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"brand_name\" : \"跎\", " + 
                    " \"locale\" : { }, " + 
                    " \"shipping_preference\" : \"NO_SHIPPING\" " + 
                    " } " + 
                    " }, " + 
                    " \"giropay\" : { " + 
                    " \"name\" : { " + 
                    " \"PbMy2bXE4NXM\" : \"zGg_2\", " + 
                    " \"2L\" : \"lmWM61yNMK\", " + 
                    " \"Xwzo\" : \"Jhh4vq\", " + 
                    " \"fVpMuLj\" : \"G\" " + 
                    " }, " + 
                    " \"country_code\" : { " + 
                    " \"mY4kSHs0EO\" : \"YqyN0\" " + 
                    " } " + 
                    " }, " + 
                    " \"mybank\" : { " + 
                    " \"name\" : { }, " + 
                    " \"country_code\" : { " + 
                    " \"JN8\" : \"RvNhgMoxYfe\", " + 
                    " \"Afgm1UO2o\" : \"Bw9lk3JVDrNQPLM\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"locale\" : { " + 
                    " \"Qxv1Plkcv\" : \"m2vWMt00o\", " + 
                    " \"UZb\" : \"slH9ss_Kx3VZv\", " + 
                    " \"nej89HE1AC\" : \"inZdVn1TXIE\", " + 
                    " \"ovYDfcXMGkm\" : \"pGmqFXnI1gU\", " + 
                    " \"2rgxhG3lgEDei1\" : \"AX\" " + 
                    " }, " + 
                    " \"shipping_preference\" : \"GET_FROM_FILE\", " + 
                    " \"cancel_url\" : \"https://www.example.com/cancelURL\" " + 
                    " } " + 
                    " }, " + 
                    " \"p24\" : { " + 
                    " \"name\" : { " + 
                    " \"z\" : \"kgNO3gXe\", " + 
                    " \"o6\" : \"r7PcbeMw3haU\", " + 
                    " \"8LeVIaF5ix\" : \"2Ao7\" " + 
                    " }, " + 
                    " \"email\" : { " + 
                    " \"H\" : \"A4Wut\", " + 
                    " \"PmXGC82\" : \"lytITgCM9xm2Yk\" " + 
                    " }, " + 
                    " \"country_code\" : { " + 
                    " \"koex20nRhL3xzMq\" : \"lva\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"return_url\" : \"https://example.com/returnUrl\", " + 
                    " \"cancel_url\" : \"https://www.example.com/cancelURL\" " + 
                    " } " + 
                    " }, " + 
                    " \"google_pay\" : { " + 
                    " \"email_address\" : { " + 
                    " \"COtSj6KQrwE7\" : \"4T7bZ8lQA8iDI5\", " + 
                    " \"FuKMnq7fEO\" : \"HtccEJOrTmfUv\" " + 
                    " }, " + 
                    " \"decrypted_token\" : { " + 
                    " \"message_expiration\" : \"1635269042807\", " + 
                    " \"payment_method\" : \"CARD\", " + 
                    " \"card\" : { " + 
                    " \"name\" : \"\", " + 
                    " \"number\" : \"2266766152400\", " + 
                    " \"last_digits\" : \"0119\", " + 
                    " \"type\" : { " + 
                    " \"7pna8R9W7lEz_\" : \"c145UzvweP\" " + 
                    " }, " + 
                    " \"brand\" : { " + 
                    " \"i\" : \"QkhMKKjt\", " + 
                    " \"KgaQld4bxJDFlEY\" : \"vEpNDRLEl7Vcben\", " + 
                    " \"z2lJH0HkPRS1fapH\" : \"eE\" " + 
                    " } " + 
                    " }, " + 
                    " \"authentication_method\" : \"CRYPTOGRAM_3DS\", " + 
                    " \"eci_indicator\" : \"佼\" " + 
                    " } " + 
                    " }, " + 
                    " \"venmo\" : { " + 
                    " \"vault_id\" : { " + 
                    " \"P0tW\" : \"HWSbnQnTPP5x10\", " + 
                    " \"hbYlGVgMN_QVT\" : \"uvNKx6h7Kq8SJ\", " + 
                    " \"idT\" : \"zkCsZ0x8ar3D\", " + 
                    " \"WXH75dKasyg9aaU\" : \"\", " + 
                    " \"8S\" : \"yX_9WcrgevB5quq\" " + 
                    " }, " + 
                    " \"attributes\" : { " + 
                    " \"vault\" : { " + 
                    " \"description\" : \"\", " + 
                    " \"customer_type\" : \"CONSUMER\", " + 
                    " \"permit_multiple_payment_tokens\" : true " + 
                    " } " + 
                    " } " + 
                    " } " + 
                    " } " + 
                    " } ")
                .post(baseUrlOfSut + "/v2/checkout/orders")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("INVALID_REQUEST"))
                .body("'details'.size()", equalTo(1))
                .body("'details'[0].'field'", containsString("prefer"))
                .body("'details'[0].'value'", containsString("e"))
                .body("'details'[0].'location'", containsString("header"))
                .body("'details'[0].'issue'", containsString("INVALID_PARAMETER_VALUE"))
                .body("'details'[0].'description'", containsString("The value of a field is invalid."))
                .body("'message'", containsString("Request is not well-formed, syntactically incorrect, or violates schema."))
                .body("'debug_id'", containsString("f91618774fb7f"))
                .body("'links'.size()", equalTo(1))
                .body("'links'[0].'href'", containsString("https://developer.paypal.com/api/rest/reference/orders/v2/errors/#INVALID_PARAMETER_VALUE"))
                .body("'links'[0].'rel'", containsString("information_link"))
                .body("'links'[0].'method'", containsString("GET"));
    }
    
    
    /**
    * Calls:
    * (404) OPTIONS:/v2/checkout/orders
    */
    @Test(timeout = 60000)
    public void test_2_optionsOnOrdersReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .options(baseUrlOfSut + "/v2/checkout/orders")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/checkout/orders/{id}
    */
    @Test(timeout = 60000)
    public void test_3_getOnOrderReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .get(baseUrlOfSut + "/v2/checkout/orders/PLX")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("RESOURCE_NOT_FOUND"))
                .body("'details'.size()", equalTo(1))
                .body("'details'[0].'issue'", containsString("INVALID_RESOURCE_ID"))
                .body("'details'[0].'description'", containsString("Specified resource ID does not exist. Please check the resource ID and try again."))
                .body("'message'", containsString("The specified resource does not exist."))
                .body("'debug_id'", containsString("f288669e61dca"))
                .body("'links'.size()", equalTo(1))
                .body("'links'[0].'href'", containsString("https://developer.paypal.com/api/rest/reference/orders/v2/errors/#INVALID_RESOURCE_ID"))
                .body("'links'[0].'rel'", containsString("information_link"))
                .body("'links'[0].'method'", containsString("GET"));
    }
    
    
    /**
    * Calls:
    * (404) OPTIONS:/v2/checkout/orders/{id}
    */
    @Test(timeout = 60000)
    public void test_4_optionsOnOrderReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .options(baseUrlOfSut + "/v2/checkout/orders/AAZ")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) OPTIONS:/v2/checkout/orders/order-update-callback
    */
    @Test(timeout = 60000)
    public void test_5_optionsOnOrder_update_callbackReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .options(baseUrlOfSut + "/v2/checkout/orders/order-update-callback")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/checkout/orders/{id}/confirm-payment-source
    * Using 1 example:
    *   (00_orders_confirm) BODY -> {"payment_source":{"paypal":{"vault_id":{}, "email_address":"customer@example.com", "name":{"prefix":"", "given_name":"John", "surname":"Doe", "middle_name":"", "suffix":"㯢"}, "birth_date":{
                    "7Axu":"w80SgLULX_9pH"
                    ,
                    "6ZWCfI4VDP9clPW":"LaqcGdHyagxoDAE"
                    ,
                    "eoLx_":"MXYp1hJAv3FGsuG"
                    ,
                    "":"atQulcGs2WyYR"
                    }, "address":{"admin_area_2":"", "country_code":"C2"}, "experience_context":{"brand_name":"EXAMPLE INC", "locale":"en-US", "shipping_preference":"SET_PROVIDED_ADDRESS", "return_url":"https://example.com/returnUrl", "cancel_url":"https://example.com/cancelUrl", "landing_page":"LOGIN", "user_action":"PAY_NOW", "payment_method_preference":"IMMEDIATE_PAYMENT_REQUIRED", "order_update_callback_config":{"callback_events":["EVOMASTER", "SHIPPING_ADDRESS"], "callback_url":"M31d6RgGfze_"}}}, "bancontact":{"name":{
                    "gFJeUaR4tDwUQO":"qGmegaU"
                    }, "country_code":{
                    "3T78K_zHnMl43f":"4"
                    }, "experience_context":{"brand_name":"짴", "return_url":""}}, "blik":{"name":{
                    "ioWwEiPYNmhFAJ":"oOo_RK2"
                    }, "country_code":{}, "email":{
                    "GBs":"iEsWO69i3Kx3"
                    ,
                    "tf_a":"hPP7mR4"
                    }, "experience_context":{"locale":{}, "shipping_preference":"NO_SHIPPING"}}, "eps":{"name":{
                    "Bbgjuk8yz5Zv5YG":"8tig_P_Lql"
                    ,
                    "UrAWMS":"qI"
                    ,
                    "4EL27WXUqhQH":"rDBjlGuwVJ6"
                    ,
                    "":"OxIi"
                    ,
                    "_SEtVqvvP0n":"JzBeLpC2PzaBTCb7"
                    }, "country_code":{}, "experience_context":{"brand_name":"馾", "shipping_preference":"GET_FROM_FILE"}}, "ideal":{"name":{
                    "5GR83eNW":"bl63"
                    }, "country_code":{
                    "LIXvONqubGouk":"Z9G3Mt"
                    ,
                    "MVUr2HP1w4kE":"2uYwvQZceVO3tBp"
                    ,
                    "":"FMWBkGkMYb4s"
                    ,
                    "NCxNlKXb":"aO7b"
                    }}, "mybank":{"name":{}, "country_code":{
                    "CgrmK7DMFsLIN":"MZ6V99X"
                    ,
                    "B":"yyAHe1FeQ"
                    ,
                    "IvPJYqyf":"t0XR"
                    ,
                    "2iWBTf":"FhqB"
                    ,
                    "EDSQ2o3060PLtr":""
                    }, "experience_context":{"locale":{
                    "MqZlOZdR6jh6N":"gEHmDpSbAFTC"
                    ,
                    "b7":"Z8EOI0Di8"
                    }, "cancel_url":"AAo1J9fATR6rpM5c"}}, "p24":{"name":{
                    "Juz":"52VnBq"
                    ,
                    "3A5FSvirnmL1":"aub22hAmMW"
                    ,
                    "nk0":"XelB6o4ck5"
                    ,
                    "fLIclNPR":"RV65AkuJiOAP9OP"
                    ,
                    "glq1SYPiAIX9":"Bzn"
                    }, "email":{
                    "u":"L_eQga6VU4ebso"
                    }, "country_code":{
                    "BBlsybNs__s8i9z6":"T2"
                    ,
                    "m_yNy":""
                    ,
                    "_0IaKFUi5":"IsDYr7S"
                    ,
                    "2GI3yZ1pR6":"MTYo2JGPYEku"
                    ,
                    "otT":"i"
                    }, "experience_context":{"brand_name":"蚕", "cancel_url":"iceosWZcRcRk"}}, "trustly":{"name":{
                    "xk1VokvPXB3":"WJUIzue"
                    ,
                    "6lnm4qvG":"F0"
                    ,
                    "Iyle2Q_TK0MKm":"eTFWw4P3"
                    }, "country_code":{}, "email":{
                    "6BJ2cWMwR":"eZRbnn6JUI"
                    ,
                    "PZqTwS5mTpc":"gqac0bJVblwZ8a"
                    ,
                    "JM0KzjEGXh9sP":"XcY"
                    }, "experience_context":{"brand_name":"츖钊", "locale":{
                    "4OngM7":"aumx"
                    ,
                    "77eqcpzQch":""
                    ,
                    "CjjX5sV":"1VEloxGw3Ce"
                    ,
                    "H3XmqG":"Yo3yCsTu9by"
                    ,
                    "3RANpSLDuONFRt9":"baqAn6lUhb5dd0mF"
                    }, "cancel_url":""}}, "google_pay":{"name":{
                    "pUr5VsNUPeIeEHVx":"usffh"
                    ,
                    "VVAmHW0eJzMn":"0Bqaoyecgxa0pij"
                    ,
                    "y79zlTcoZEINmIpk":"W04"
                    }, "phone_number":{"country_code":"8", "national_number":"00"}, "decrypted_token":{"message_id":"飵ꡃ", "message_expiration":"7281376062053", "payment_method":"EVOMASTER", "card":{"name":"읟粁Ⓗ", "last_digits":"61", "type":{
                    "1UllDixSBxkZh":"WprDe"
                    ,
                    "9RTr0C6C":"kYNEpNiiGu"
                    ,
                    "32EGrIy7YQDfV4Op":""
                    }}, "authentication_method":"CRYPTOGRAM_3DS", "cryptogram":""}, "assurance_details":{"account_verified":true, "card_holder_authenticated":true}}, "crypto":{"country_code":{
                    "A8":"YZn"
                    ,
                    "rUjzGZpW":""
                    ,
                    "d7":"bgHp6QMU"
                    ,
                    "_1RYZRJvKs":"k4B"
                    ,
                    "L07hlMzWsBE":"IXdg_05N"
                    }, "name":{"prefix":"ﵩ", "given_name":"", "surname":""}, "experience_context":{"locale":{
                    "WK":"Vm5thO"
                    ,
                    "TSRuWV":"WxM"
                    ,
                    "0WyfXDfcgWZmB9":"PwSzCLJYEr"
                    ,
                    "":"8DWIpOtj4XYW"
                    ,
                    "32t":"uUj8OxxQD"
                    }, "return_url":"", "cancel_url":"BWEAOau"}}}, "application_context":{"brand_name":"쵥"}}
    */
    @Test(timeout = 60000)
    public void test_6_postOnConfirm_payment_sourceReturns400() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .header("PayPal-Client-Metadata-Id", ")")
                .header("PayPal-Auth-Assertion", "")
                .header("Prefer", "ik")
                .contentType("application/json")
                .body(" { " + 
                    " \"payment_source\" : { " + 
                    " \"paypal\" : { " + 
                    " \"vault_id\" : { }, " + 
                    " \"email_address\" : \"customer@example.com\", " + 
                    " \"name\" : { " + 
                    " \"prefix\" : \"\", " + 
                    " \"given_name\" : \"John\", " + 
                    " \"surname\" : \"Doe\", " + 
                    " \"middle_name\" : \"\", " + 
                    " \"suffix\" : \"㯢\" " + 
                    " }, " + 
                    " \"birth_date\" : { " + 
                    " \"7Axu\" : \"w80SgLULX_9pH\", " + 
                    " \"6ZWCfI4VDP9clPW\" : \"LaqcGdHyagxoDAE\", " + 
                    " \"eoLx_\" : \"MXYp1hJAv3FGsuG\", " + 
                    " \"\" : \"atQulcGs2WyYR\" " + 
                    " }, " + 
                    " \"address\" : { " + 
                    " \"admin_area_2\" : \"\", " + 
                    " \"country_code\" : \"C2\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"brand_name\" : \"EXAMPLE INC\", " + 
                    " \"locale\" : \"en-US\", " + 
                    " \"shipping_preference\" : \"SET_PROVIDED_ADDRESS\", " + 
                    " \"return_url\" : \"https://example.com/returnUrl\", " + 
                    " \"cancel_url\" : \"https://example.com/cancelUrl\", " + 
                    " \"landing_page\" : \"LOGIN\", " + 
                    " \"user_action\" : \"PAY_NOW\", " + 
                    " \"payment_method_preference\" : \"IMMEDIATE_PAYMENT_REQUIRED\", " + 
                    " \"order_update_callback_config\" : { " + 
                    " \"callback_events\" : [ \"EVOMASTER\", \"SHIPPING_ADDRESS\" ], " + 
                    " \"callback_url\" : \"M31d6RgGfze_\" " + 
                    " } " + 
                    " } " + 
                    " }, " + 
                    " \"bancontact\" : { " + 
                    " \"name\" : { " + 
                    " \"gFJeUaR4tDwUQO\" : \"qGmegaU\" " + 
                    " }, " + 
                    " \"country_code\" : { " + 
                    " \"3T78K_zHnMl43f\" : \"4\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"brand_name\" : \"짴\", " + 
                    " \"return_url\" : \"\" " + 
                    " } " + 
                    " }, " + 
                    " \"blik\" : { " + 
                    " \"name\" : { " + 
                    " \"ioWwEiPYNmhFAJ\" : \"oOo_RK2\" " + 
                    " }, " + 
                    " \"country_code\" : { }, " + 
                    " \"email\" : { " + 
                    " \"GBs\" : \"iEsWO69i3Kx3\", " + 
                    " \"tf_a\" : \"hPP7mR4\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"locale\" : { }, " + 
                    " \"shipping_preference\" : \"NO_SHIPPING\" " + 
                    " } " + 
                    " }, " + 
                    " \"eps\" : { " + 
                    " \"name\" : { " + 
                    " \"Bbgjuk8yz5Zv5YG\" : \"8tig_P_Lql\", " + 
                    " \"UrAWMS\" : \"qI\", " + 
                    " \"4EL27WXUqhQH\" : \"rDBjlGuwVJ6\", " + 
                    " \"\" : \"OxIi\", " + 
                    " \"_SEtVqvvP0n\" : \"JzBeLpC2PzaBTCb7\" " + 
                    " }, " + 
                    " \"country_code\" : { }, " + 
                    " \"experience_context\" : { " + 
                    " \"brand_name\" : \"馾\", " + 
                    " \"shipping_preference\" : \"GET_FROM_FILE\" " + 
                    " } " + 
                    " }, " + 
                    " \"ideal\" : { " + 
                    " \"name\" : { " + 
                    " \"5GR83eNW\" : \"bl63\" " + 
                    " }, " + 
                    " \"country_code\" : { " + 
                    " \"LIXvONqubGouk\" : \"Z9G3Mt\", " + 
                    " \"MVUr2HP1w4kE\" : \"2uYwvQZceVO3tBp\", " + 
                    " \"\" : \"FMWBkGkMYb4s\", " + 
                    " \"NCxNlKXb\" : \"aO7b\" " + 
                    " } " + 
                    " }, " + 
                    " \"mybank\" : { " + 
                    " \"name\" : { }, " + 
                    " \"country_code\" : { " + 
                    " \"CgrmK7DMFsLIN\" : \"MZ6V99X\", " + 
                    " \"B\" : \"yyAHe1FeQ\", " + 
                    " \"IvPJYqyf\" : \"t0XR\", " + 
                    " \"2iWBTf\" : \"FhqB\", " + 
                    " \"EDSQ2o3060PLtr\" : \"\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"locale\" : { " + 
                    " \"MqZlOZdR6jh6N\" : \"gEHmDpSbAFTC\", " + 
                    " \"b7\" : \"Z8EOI0Di8\" " + 
                    " }, " + 
                    " \"cancel_url\" : \"AAo1J9fATR6rpM5c\" " + 
                    " } " + 
                    " }, " + 
                    " \"p24\" : { " + 
                    " \"name\" : { " + 
                    " \"Juz\" : \"52VnBq\", " + 
                    " \"3A5FSvirnmL1\" : \"aub22hAmMW\", " + 
                    " \"nk0\" : \"XelB6o4ck5\", " + 
                    " \"fLIclNPR\" : \"RV65AkuJiOAP9OP\", " + 
                    " \"glq1SYPiAIX9\" : \"Bzn\" " + 
                    " }, " + 
                    " \"email\" : { " + 
                    " \"u\" : \"L_eQga6VU4ebso\" " + 
                    " }, " + 
                    " \"country_code\" : { " + 
                    " \"BBlsybNs__s8i9z6\" : \"T2\", " + 
                    " \"m_yNy\" : \"\", " + 
                    " \"_0IaKFUi5\" : \"IsDYr7S\", " + 
                    " \"2GI3yZ1pR6\" : \"MTYo2JGPYEku\", " + 
                    " \"otT\" : \"i\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"brand_name\" : \"蚕\", " + 
                    " \"cancel_url\" : \"iceosWZcRcRk\" " + 
                    " } " + 
                    " }, " + 
                    " \"trustly\" : { " + 
                    " \"name\" : { " + 
                    " \"xk1VokvPXB3\" : \"WJUIzue\", " + 
                    " \"6lnm4qvG\" : \"F0\", " + 
                    " \"Iyle2Q_TK0MKm\" : \"eTFWw4P3\" " + 
                    " }, " + 
                    " \"country_code\" : { }, " + 
                    " \"email\" : { " + 
                    " \"6BJ2cWMwR\" : \"eZRbnn6JUI\", " + 
                    " \"PZqTwS5mTpc\" : \"gqac0bJVblwZ8a\", " + 
                    " \"JM0KzjEGXh9sP\" : \"XcY\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"brand_name\" : \"츖钊\", " + 
                    " \"locale\" : { " + 
                    " \"4OngM7\" : \"aumx\", " + 
                    " \"77eqcpzQch\" : \"\", " + 
                    " \"CjjX5sV\" : \"1VEloxGw3Ce\", " + 
                    " \"H3XmqG\" : \"Yo3yCsTu9by\", " + 
                    " \"3RANpSLDuONFRt9\" : \"baqAn6lUhb5dd0mF\" " + 
                    " }, " + 
                    " \"cancel_url\" : \"\" " + 
                    " } " + 
                    " }, " + 
                    " \"google_pay\" : { " + 
                    " \"name\" : { " + 
                    " \"pUr5VsNUPeIeEHVx\" : \"usffh\", " + 
                    " \"VVAmHW0eJzMn\" : \"0Bqaoyecgxa0pij\", " + 
                    " \"y79zlTcoZEINmIpk\" : \"W04\" " + 
                    " }, " + 
                    " \"phone_number\" : { " + 
                    " \"country_code\" : \"8\", " + 
                    " \"national_number\" : \"00\" " + 
                    " }, " + 
                    " \"decrypted_token\" : { " + 
                    " \"message_id\" : \"飵ꡃ\", " + 
                    " \"message_expiration\" : \"7281376062053\", " + 
                    " \"payment_method\" : \"EVOMASTER\", " + 
                    " \"card\" : { " + 
                    " \"name\" : \"읟粁Ⓗ\", " + 
                    " \"last_digits\" : \"61\", " + 
                    " \"type\" : { " + 
                    " \"1UllDixSBxkZh\" : \"WprDe\", " + 
                    " \"9RTr0C6C\" : \"kYNEpNiiGu\", " + 
                    " \"32EGrIy7YQDfV4Op\" : \"\" " + 
                    " } " + 
                    " }, " + 
                    " \"authentication_method\" : \"CRYPTOGRAM_3DS\", " + 
                    " \"cryptogram\" : \"\" " + 
                    " }, " + 
                    " \"assurance_details\" : { " + 
                    " \"account_verified\" : true, " + 
                    " \"card_holder_authenticated\" : true " + 
                    " } " + 
                    " }, " + 
                    " \"crypto\" : { " + 
                    " \"country_code\" : { " + 
                    " \"A8\" : \"YZn\", " + 
                    " \"rUjzGZpW\" : \"\", " + 
                    " \"d7\" : \"bgHp6QMU\", " + 
                    " \"_1RYZRJvKs\" : \"k4B\", " + 
                    " \"L07hlMzWsBE\" : \"IXdg_05N\" " + 
                    " }, " + 
                    " \"name\" : { " + 
                    " \"prefix\" : \"ﵩ\", " + 
                    " \"given_name\" : \"\", " + 
                    " \"surname\" : \"\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"locale\" : { " + 
                    " \"WK\" : \"Vm5thO\", " + 
                    " \"TSRuWV\" : \"WxM\", " + 
                    " \"0WyfXDfcgWZmB9\" : \"PwSzCLJYEr\", " + 
                    " \"\" : \"8DWIpOtj4XYW\", " + 
                    " \"32t\" : \"uUj8OxxQD\" " + 
                    " }, " + 
                    " \"return_url\" : \"\", " + 
                    " \"cancel_url\" : \"BWEAOau\" " + 
                    " } " + 
                    " } " + 
                    " }, " + 
                    " \"application_context\" : { " + 
                    " \"brand_name\" : \"쵥\" " + 
                    " } " + 
                    " } ")
                .post(baseUrlOfSut + "/v2/checkout/orders/3N0/confirm-payment-source")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("INVALID_REQUEST"))
                .body("'details'.size()", equalTo(1))
                .body("'details'[0].'field'", containsString("prefer"))
                .body("'details'[0].'value'", containsString("ik"))
                .body("'details'[0].'location'", containsString("header"))
                .body("'details'[0].'issue'", containsString("INVALID_PARAMETER_VALUE"))
                .body("'details'[0].'description'", containsString("The value of a field is invalid."))
                .body("'message'", containsString("Request is not well-formed, syntactically incorrect, or violates schema."))
                .body("'debug_id'", containsString("f840482f6e12c"))
                .body("'links'.size()", equalTo(1))
                .body("'links'[0].'href'", containsString("https://developer.paypal.com/api/rest/reference/orders/v2/errors/#INVALID_PARAMETER_VALUE"))
                .body("'links'[0].'rel'", containsString("information_link"))
                .body("'links'[0].'method'", containsString("GET"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/checkout/orders/{id}/track
    */
    @Test(timeout = 60000)
    public void test_7_postOnTrackReturns400() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .header("PayPal-Auth-Assertion", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"tracking_number\" : \"\", " + 
                    " \"carrier\" : \"LOGISYSTEMS_SFTP\", " + 
                    " \"carrier_name_other\" : \"㋅\", " + 
                    " \"capture_id\" : \"C\", " + 
                    " \"notify_payer\" : true " + 
                    " } ")
                .post(baseUrlOfSut + "/v2/checkout/orders/OJ/track")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("INVALID_REQUEST"))
                .body("'message'", containsString("Request is not well-formed, syntactically incorrect, or violates schema."))
                .body("'debug_id'", containsString("f115952e32146"))
                .body("'details'.size()", equalTo(1))
                .body("'details'[0].'field'", containsString("/tracking_number"))
                .body("'details'[0].'value'", containsString(""))
                .body("'details'[0].'location'", containsString("body"))
                .body("'details'[0].'issue'", containsString("INVALID_STRING_LENGTH"))
                .body("'details'[0].'description'", containsString("The value of a field is either too short or too long."))
                .body("'links'.size()", equalTo(1))
                .body("'links'[0].'href'", containsString("https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_STRING_LENGTH"))
                .body("'links'[0].'rel'", containsString("information_link"))
                .body("'links'[0].'encType'", containsString("application/json"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/checkout/orders/{id}/authorize
    * Using 4 examples:
    *   (guid) HEADER: PayPal-Client-Metadata-Id -> 1295065d-6f34-42dc-ac65-fac0c86af250
    *   (orders_authorize_paypal_wallet_vault_id) BODY -> {"payment_source":{"token":{"id":"RhM", "type":"BILLING_AGREEMENT"}, "paypal":{"vault_id":"nkq2y9g", "name":{"given_name":"", "middle_name":"⿜"}, "phone":{"phone_type":"MOBILE", "phone_number":{"national_number":"28"}}, "birth_date":{
                    "1xVpdwbm3PFrEclq":"4Z0pJd1sIHnDvM1A"
                    }, "address":{"address_line_1":"", "address_line_3":"", "admin_area_4":"", "postal_code":"", "country_code":"C2", "address_details":{"street_name":"껿", "street_type":"䋭", "delivery_service":"얀쐑", "sub_building":"礸俉"}}, "attributes":{"customer":{}}}, "bancontact":{"name":{
                    "TNsIQAsCULc":"7kPSpFu91YRClM3"
                    ,
                    "Mk":"y"
                    }, "country_code":{
                    "Tzg5h":"7"
                    ,
                    "hftZfM8jdbLCu6C":"HTtj"
                    }}, "eps":{"name":{
                    "mNblQ7":"zES_aPnVrsywPQk"
                    }, "country_code":{}}, "sofort":{"name":{}, "country_code":{
                    "_IrMQpmO5iA7lC":"bUzV_Y0dSp"
                    ,
                    "r31NXrdfnxj":"akSmj_aE"
                    ,
                    "RvznbHLD66m173FC":"J1f9FhTH5wY"
                    }, "experience_context":{"brand_name":"統", "shipping_preference":"NO_SHIPPING"}}, "apple_pay":{"id":"", "phone_number":{"national_number":"5"}, "decrypted_token":{"tokenized_card":{"id":{
                    "XSr8pSit":"PWfiI6fHqUFspHL"
                    }, "security_code":"157", "last_digits":"525", "card_type":{
                    "ty":"yRrlPrSl7iuQ"
                    ,
                    "TR8GZ0Z4":"ToZqmGoZ6t"
                    ,
                    "inti":"pBDT7aWMiauypND"
                    ,
                    "":"H0tmtnPerlwVtG"
                    }, "type":{
                    "HEZ2CjB":"KI"
                    ,
                    "I54Y9iZT":"DIFji82bM"
                    ,
                    "j7Y6L":"alz"
                    ,
                    "R":"ppo4H2rq"
                    ,
                    "PXZ5nbv":"FZ_4U"
                    }, "billing_address":{}, "attributes":{
                    "t8LRB":"g7MQMVO5565"
                    ,
                    "3IfaazIdRz7IEe69":"cOX66ws"
                    ,
                    "BiFeq0fhUfFCPMF":"gSMtZtKe"
                    ,
                    "":""
                    }}, "device_manufacturer_id":"켧", "payment_data_type":"3DSECURE", "payment_data":{"cryptogram":"⣱", "pin":"嬹励"}}, "vault_id":{
                    "NxomGVSlmUU6ios":"Ds"
                    ,
                    "zzM8NsyD":"yAtnzrwyRU"
                    ,
                    "":"2"
                    ,
                    "sZgD2oR8Ks":"ya"
                    ,
                    "VR566H":"6xptKU"
                    }}, "google_pay":{"email_address":{}, "phone_number":{"country_code":"31", "national_number":"121"}}, "venmo":{"vault_id":{
                    "_4OQesKv24VY4gL7":"hQhaSJ5qQ9s"
                    ,
                    "QuB8EK":"Mi99qrCWa1"
                    }, "email_address":{
                    "RbilfGGmkBsiccoN":"pRy4RmuNPeOn2p_3"
                    ,
                    "sowouQl1":"ZIlq8"
                    }, "experience_context":{"shipping_preference":"SET_PROVIDED_ADDRESS", "user_action":"PAY_NOW"}, "attributes":{"customer":{
                    "ob5s79k7pnF7F7o":"JJq"
                    ,
                    "6yi59Q_lzSVt":"R4k7eZW3oh7IIe"
                    ,
                    "pbf5HEh6yNwB":"LXs0cQxekD49gS"
                    }}}}}
    *   (orders_authorize_paypal_wallet_vault_id) HEADER: PayPal-Request-Id -> 7b92603e-77ed-4896-8e78-5dea2050476a
    *   (orders_authorize_paypal_wallet_vault_id) PATH: id -> 5O190127TN364715T
    */
    @Test(timeout = 60000)
    public void test_8_postOnAuthorizeReturns400() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .header("PayPal-Request-Id", "7b92603e-77ed-4896-8e78-5dea2050476a")
                .header("PayPal-Client-Metadata-Id", "1295065d-6f34-42dc-ac65-fac0c86af250")
                .header("PayPal-Auth-Assertion", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"payment_source\" : { " + 
                    " \"token\" : { " + 
                    " \"id\" : \"RhM\", " + 
                    " \"type\" : \"BILLING_AGREEMENT\" " + 
                    " }, " + 
                    " \"paypal\" : { " + 
                    " \"vault_id\" : \"nkq2y9g\", " + 
                    " \"name\" : { " + 
                    " \"given_name\" : \"\", " + 
                    " \"middle_name\" : \"⿜\" " + 
                    " }, " + 
                    " \"phone\" : { " + 
                    " \"phone_type\" : \"MOBILE\", " + 
                    " \"phone_number\" : { " + 
                    " \"national_number\" : \"28\" " + 
                    " } " + 
                    " }, " + 
                    " \"birth_date\" : { " + 
                    " \"1xVpdwbm3PFrEclq\" : \"4Z0pJd1sIHnDvM1A\" " + 
                    " }, " + 
                    " \"address\" : { " + 
                    " \"address_line_1\" : \"\", " + 
                    " \"address_line_3\" : \"\", " + 
                    " \"admin_area_4\" : \"\", " + 
                    " \"postal_code\" : \"\", " + 
                    " \"country_code\" : \"C2\", " + 
                    " \"address_details\" : { " + 
                    " \"street_name\" : \"껿\", " + 
                    " \"street_type\" : \"䋭\", " + 
                    " \"delivery_service\" : \"얀쐑\", " + 
                    " \"sub_building\" : \"礸俉\" " + 
                    " } " + 
                    " }, " + 
                    " \"attributes\" : { " + 
                    " \"customer\" : { } " + 
                    " } " + 
                    " }, " + 
                    " \"bancontact\" : { " + 
                    " \"name\" : { " + 
                    " \"TNsIQAsCULc\" : \"7kPSpFu91YRClM3\", " + 
                    " \"Mk\" : \"y\" " + 
                    " }, " + 
                    " \"country_code\" : { " + 
                    " \"Tzg5h\" : \"7\", " + 
                    " \"hftZfM8jdbLCu6C\" : \"HTtj\" " + 
                    " } " + 
                    " }, " + 
                    " \"eps\" : { " + 
                    " \"name\" : { " + 
                    " \"mNblQ7\" : \"zES_aPnVrsywPQk\" " + 
                    " }, " + 
                    " \"country_code\" : { } " + 
                    " }, " + 
                    " \"sofort\" : { " + 
                    " \"name\" : { }, " + 
                    " \"country_code\" : { " + 
                    " \"_IrMQpmO5iA7lC\" : \"bUzV_Y0dSp\", " + 
                    " \"r31NXrdfnxj\" : \"akSmj_aE\", " + 
                    " \"RvznbHLD66m173FC\" : \"J1f9FhTH5wY\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"brand_name\" : \"統\", " + 
                    " \"shipping_preference\" : \"NO_SHIPPING\" " + 
                    " } " + 
                    " }, " + 
                    " \"apple_pay\" : { " + 
                    " \"id\" : \"\", " + 
                    " \"phone_number\" : { " + 
                    " \"national_number\" : \"5\" " + 
                    " }, " + 
                    " \"decrypted_token\" : { " + 
                    " \"tokenized_card\" : { " + 
                    " \"id\" : { " + 
                    " \"XSr8pSit\" : \"PWfiI6fHqUFspHL\" " + 
                    " }, " + 
                    " \"security_code\" : \"157\", " + 
                    " \"last_digits\" : \"525\", " + 
                    " \"card_type\" : { " + 
                    " \"ty\" : \"yRrlPrSl7iuQ\", " + 
                    " \"TR8GZ0Z4\" : \"ToZqmGoZ6t\", " + 
                    " \"inti\" : \"pBDT7aWMiauypND\", " + 
                    " \"\" : \"H0tmtnPerlwVtG\" " + 
                    " }, " + 
                    " \"type\" : { " + 
                    " \"HEZ2CjB\" : \"KI\", " + 
                    " \"I54Y9iZT\" : \"DIFji82bM\", " + 
                    " \"j7Y6L\" : \"alz\", " + 
                    " \"R\" : \"ppo4H2rq\", " + 
                    " \"PXZ5nbv\" : \"FZ_4U\" " + 
                    " }, " + 
                    " \"billing_address\" : { }, " + 
                    " \"attributes\" : { " + 
                    " \"t8LRB\" : \"g7MQMVO5565\", " + 
                    " \"3IfaazIdRz7IEe69\" : \"cOX66ws\", " + 
                    " \"BiFeq0fhUfFCPMF\" : \"gSMtZtKe\", " + 
                    " \"\" : \"\" " + 
                    " } " + 
                    " }, " + 
                    " \"device_manufacturer_id\" : \"켧\", " + 
                    " \"payment_data_type\" : \"3DSECURE\", " + 
                    " \"payment_data\" : { " + 
                    " \"cryptogram\" : \"⣱\", " + 
                    " \"pin\" : \"嬹励\" " + 
                    " } " + 
                    " }, " + 
                    " \"vault_id\" : { " + 
                    " \"NxomGVSlmUU6ios\" : \"Ds\", " + 
                    " \"zzM8NsyD\" : \"yAtnzrwyRU\", " + 
                    " \"\" : \"2\", " + 
                    " \"sZgD2oR8Ks\" : \"ya\", " + 
                    " \"VR566H\" : \"6xptKU\" " + 
                    " } " + 
                    " }, " + 
                    " \"google_pay\" : { " + 
                    " \"email_address\" : { }, " + 
                    " \"phone_number\" : { " + 
                    " \"country_code\" : \"31\", " + 
                    " \"national_number\" : \"121\" " + 
                    " } " + 
                    " }, " + 
                    " \"venmo\" : { " + 
                    " \"vault_id\" : { " + 
                    " \"_4OQesKv24VY4gL7\" : \"hQhaSJ5qQ9s\", " + 
                    " \"QuB8EK\" : \"Mi99qrCWa1\" " + 
                    " }, " + 
                    " \"email_address\" : { " + 
                    " \"RbilfGGmkBsiccoN\" : \"pRy4RmuNPeOn2p_3\", " + 
                    " \"sowouQl1\" : \"ZIlq8\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"shipping_preference\" : \"SET_PROVIDED_ADDRESS\", " + 
                    " \"user_action\" : \"PAY_NOW\" " + 
                    " }, " + 
                    " \"attributes\" : { " + 
                    " \"customer\" : { " + 
                    " \"ob5s79k7pnF7F7o\" : \"JJq\", " + 
                    " \"6yi59Q_lzSVt\" : \"R4k7eZW3oh7IIe\", " + 
                    " \"pbf5HEh6yNwB\" : \"LXs0cQxekD49gS\" " + 
                    " } " + 
                    " } " + 
                    " } " + 
                    " } " + 
                    " } ")
                .post(baseUrlOfSut + "/v2/checkout/orders/5O190127TN364715T/authorize")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("INVALID_REQUEST"))
                .body("'message'", containsString("Request is not well-formed, syntactically incorrect, or violates schema."))
                .body("'debug_id'", containsString("f325435efefe8"))
                .body("'details'.size()", equalTo(1))
                .body("'details'[0].'field'", containsString("/payment_source/paypal/birth_date"))
                .body("'details'[0].'location'", containsString("body"))
                .body("'details'[0].'issue'", containsString("MALFORMED_REQUEST_JSON"))
                .body("'details'[0].'description'", containsString("The request JSON is not well formed."))
                .body("'links'.size()", equalTo(1))
                .body("'links'[0].'href'", containsString("https://developer.paypal.com/docs/api/orders/v2/#error-MALFORMED_REQUEST_JSON"))
                .body("'links'[0].'rel'", containsString("information_link"))
                .body("'links'[0].'encType'", containsString("application/json"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/checkout/orders/{id}/capture
    */
    @Test(timeout = 60000)
    public void test_9_postOnCaptureReturns400() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .header("PayPal-Request-Id", "泮ꗘ")
                .header("Prefer", "Tv")
                .header("PayPal-Client-Metadata-Id", "i")
                .contentType("application/json")
                .post(baseUrlOfSut + "/v2/checkout/orders/U/capture")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("INVALID_REQUEST"))
                .body("'details'.size()", equalTo(1))
                .body("'details'[0].'field'", containsString("prefer"))
                .body("'details'[0].'value'", containsString("Tv"))
                .body("'details'[0].'location'", containsString("header"))
                .body("'details'[0].'issue'", containsString("INVALID_PARAMETER_VALUE"))
                .body("'details'[0].'description'", containsString("The value of a field is invalid."))
                .body("'message'", containsString("Request is not well-formed, syntactically incorrect, or violates schema."))
                .body("'debug_id'", containsString("f5058036f1058"))
                .body("'links'.size()", equalTo(1))
                .body("'links'[0].'href'", containsString("https://developer.paypal.com/api/rest/reference/orders/v2/errors/#INVALID_PARAMETER_VALUE"))
                .body("'links'[0].'rel'", containsString("information_link"))
                .body("'links'[0].'method'", containsString("GET"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/checkout/orders/{id}/authorize
    * Using 3 examples:
    *   (authorize_422_unprocessable_entity_payment_denied) BODY -> {"payment_source":{"card":{"name":"笵慯鰍", "expiry":{
                    "Dp8":"DEkhi9oEXJN"
                    ,
                    "ugmkmxkoB3Yg":"r3v3dJi"
                    ,
                    "PdRsLB5hwcA9g":"nuJMlMdIzym2SH_"
                    ,
                    "hwcqz":"_2lDx"
                    }, "vault_id":"8cg02452we902502k", "single_use_token":{}, "stored_credential":{"payment_initiator":"MERCHANT", "payment_type":"UNSCHEDULED"}, "experience_context":{"return_url":{}}}, "paypal":{"email_address":{
                    "7vsbfj1pVvdcdvE":"wDr6"
                    ,
                    "0xRv":"ANxJXO"
                    ,
                    "Sv":"pyA6_8HUyliQKpG"
                    }, "name":{"surname":"狸", "suffix":""}, "birth_date":{}, "tax_info":{"tax_id":"ጡ3㙔⽽", "tax_id_type":"BR_CPF"}, "address":{"address_line_1":"⠯", "admin_area_4":"", "admin_area_3":"", "admin_area_2":"ҍᕼ", "postal_code":"", "country_code":"C2", "address_details":{"street_type":"琡", "building_name":"굸", "sub_building":"䗁"}}, "experience_context":{"brand_name":"꯰", "locale":{
                    "Wz5kxUhha79jN2y":"FwWRs3T9Z4jl"
                    }, "order_update_callback_config":{"callback_events":["EVOMASTER", "SHIPPING_OPTIONS", "SHIPPING_ADDRESS"], "callback_url":"tK7c2oWtkjK6"}}, "stored_credential":{"payment_initiator":"MERCHANT", "charge_pattern":{
                    "LQQDKObywKoi":"gRNXqNdKcx_rfy"
                    ,
                    "v6X6gchz":"pnP"
                    ,
                    "qT_Yv2aenT":"WIX9vh"
                    ,
                    "Vhm6SNxiE0":"1gkIsyc3C"
                    }}}, "eps":{"name":{
                    "o3ufuErI3":"ouQxAStKZ"
                    ,
                    "9Q":"C"
                    ,
                    "U2AZ5JP2gp8F6db":"TR"
                    ,
                    "b8BUkbw":"wzQM"
                    ,
                    "vwGtcWEZmJMj":"vrCAliFs1Mg"
                    }, "country_code":{
                    "jEgUY":"Ho16Dp9VF0Q1"
                    ,
                    "QciIW6rJiTOK":"1u6Cc77EWt7lzHP"
                    ,
                    "l3XY9YklwKH":"3oXjats"
                    }, "experience_context":{"brand_name":""}}, "giropay":{"name":{
                    "HShkPdtt9":"7yk"
                    }, "country_code":{
                    "j_d_Yvdp0":"pn5KfULdNGvEcJMX"
                    ,
                    "8iTrGlgcUA":"VSaaEQG"
                    ,
                    "MJj4":"ku"
                    ,
                    "3E6Bzq":""
                    ,
                    "I2OVbWImj5hI0E":"f1RrKJ3MfpNM"
                    }, "experience_context":{"brand_name":"茟", "cancel_url":"https://example.com/cancelUrl"}}, "ideal":{"name":{
                    "Cq8oEfsCyT_Ah":"7_7LFI77k"
                    ,
                    "ZE4JeKr3Kyq0b69d":"e7Mrai8goyWyY"
                    ,
                    "muI18wdjhK":"4xH0BofazcHH85"
                    ,
                    "c19HhAt":"1"
                    }, "country_code":{
                    "XKdCWGCUU3lWkWzu":"_vZR8h"
                    ,
                    "Ow7hnpy_3":"R2rDrieWZDReF"
                    ,
                    "gf_7onIHE":"6HToTv"
                    ,
                    "oTv55Cs5Ia":"ELcPCgoebDMIfn4"
                    ,
                    "CKVUwt0UdKjZ":"kBvhnd34"
                    }}, "mybank":{"name":{}, "country_code":{
                    "U97oJc3ECzu7VOdI":"WtCYNy"
                    ,
                    "4g":"VWz4GWc2"
                    ,
                    "Zhj44AjvXMmpIQ":"MzRd"
                    ,
                    "5FYzP":"yOS"
                    }}, "p24":{"name":{
                    "AYO0mt1dv":""
                    }, "email":{
                    "5ygzm96ApPkplNIe":"xWq8Tm"
                    ,
                    "LQH":"kOSJBtqoKf7W"
                    }, "country_code":{
                    "Jyxr":"klFMWvAAHb9aCS"
                    ,
                    "MH6S41On5t":"NXfmLEcViB9QFOWJ"
                    ,
                    "oz2QPX26da_vAAFx":"gnoTb"
                    }}, "apple_pay":{"id":"䛪", "name":{
                    "8ozAO870":"ZiByg"
                    ,
                    "DvsLmft377m0":"tTmaxaNI"
                    ,
                    "VMtoTf56jk5g5w":"hm0T0Anue"
                    ,
                    "IRF89":"R7H9QiWU6ahjm"
                    }, "phone_number":{"national_number":"4"}, "decrypted_token":{"tokenized_card":{"name":"䝔", "number":"306103883786064", "security_code":"530", "last_digits":"35", "card_type":{}, "type":{}, "attributes":{
                    "bYBXm41wBbDZ":"aRb"
                    ,
                    "PdWv21mO58":"RCj"
                    ,
                    "wUmUjCuD1ZPCWtL":"j5PjNtopCfFeI"
                    }}, "device_manufacturer_id":"", "payment_data_type":"EMV"}, "stored_credential":{"payment_initiator":"MERCHANT", "payment_type":"EVOMASTER", "usage":"SUBSEQUENT"}, "vault_id":{
                    "HLKXB3r21JH9r2Wm":"MnoYnQGz"
                    ,
                    "cH":"fxDUwixzSYBKL_"
                    }, "experience_context":{"return_url":"https://www.example.com/returnURL", "cancel_url":"https://www.example.com/cancelURL"}}, "venmo":{"vault_id":{}, "email_address":{
                    "Ufn7o9YbRa3q":"DvdW8Q"
                    }}}}
    *   (authorize_422_unprocessable_entity_payment_denied) HEADER: PayPal-Request-Id -> 7b92603e-77ed-4896-8e78-5dea2050476a
    *   (authorize_422_unprocessable_entity_payment_denied) PATH: id -> 5O190127TN364715T
    */
    @Test(timeout = 60000)
    public void test_10_postOnAuthorizeReturns400() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .header("PayPal-Request-Id", "7b92603e-77ed-4896-8e78-5dea2050476a")
                .header("Prefer", "-l")
                .header("PayPal-Client-Metadata-Id", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"payment_source\" : { " + 
                    " \"card\" : { " + 
                    " \"name\" : \"笵慯鰍\", " + 
                    " \"expiry\" : { " + 
                    " \"Dp8\" : \"DEkhi9oEXJN\", " + 
                    " \"ugmkmxkoB3Yg\" : \"r3v3dJi\", " + 
                    " \"PdRsLB5hwcA9g\" : \"nuJMlMdIzym2SH_\", " + 
                    " \"hwcqz\" : \"_2lDx\" " + 
                    " }, " + 
                    " \"vault_id\" : \"8cg02452we902502k\", " + 
                    " \"single_use_token\" : { }, " + 
                    " \"stored_credential\" : { " + 
                    " \"payment_initiator\" : \"MERCHANT\", " + 
                    " \"payment_type\" : \"UNSCHEDULED\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"return_url\" : { } " + 
                    " } " + 
                    " }, " + 
                    " \"paypal\" : { " + 
                    " \"email_address\" : { " + 
                    " \"7vsbfj1pVvdcdvE\" : \"wDr6\", " + 
                    " \"0xRv\" : \"ANxJXO\", " + 
                    " \"Sv\" : \"pyA6_8HUyliQKpG\" " + 
                    " }, " + 
                    " \"name\" : { " + 
                    " \"surname\" : \"狸\", " + 
                    " \"suffix\" : \"\" " + 
                    " }, " + 
                    " \"birth_date\" : { }, " + 
                    " \"tax_info\" : { " + 
                    " \"tax_id\" : \"ጡ3㙔⽽\", " + 
                    " \"tax_id_type\" : \"BR_CPF\" " + 
                    " }, " + 
                    " \"address\" : { " + 
                    " \"address_line_1\" : \"⠯\", " + 
                    " \"admin_area_4\" : \"\", " + 
                    " \"admin_area_3\" : \"\", " + 
                    " \"admin_area_2\" : \"ҍᕼ\", " + 
                    " \"postal_code\" : \"\", " + 
                    " \"country_code\" : \"C2\", " + 
                    " \"address_details\" : { " + 
                    " \"street_type\" : \"琡\", " + 
                    " \"building_name\" : \"굸\", " + 
                    " \"sub_building\" : \"䗁\" " + 
                    " } " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"brand_name\" : \"꯰\", " + 
                    " \"locale\" : { " + 
                    " \"Wz5kxUhha79jN2y\" : \"FwWRs3T9Z4jl\" " + 
                    " }, " + 
                    " \"order_update_callback_config\" : { " + 
                    " \"callback_events\" : [ \"EVOMASTER\", \"SHIPPING_OPTIONS\", \"SHIPPING_ADDRESS\" ], " + 
                    " \"callback_url\" : \"tK7c2oWtkjK6\" " + 
                    " } " + 
                    " }, " + 
                    " \"stored_credential\" : { " + 
                    " \"payment_initiator\" : \"MERCHANT\", " + 
                    " \"charge_pattern\" : { " + 
                    " \"LQQDKObywKoi\" : \"gRNXqNdKcx_rfy\", " + 
                    " \"v6X6gchz\" : \"pnP\", " + 
                    " \"qT_Yv2aenT\" : \"WIX9vh\", " + 
                    " \"Vhm6SNxiE0\" : \"1gkIsyc3C\" " + 
                    " } " + 
                    " } " + 
                    " }, " + 
                    " \"eps\" : { " + 
                    " \"name\" : { " + 
                    " \"o3ufuErI3\" : \"ouQxAStKZ\", " + 
                    " \"9Q\" : \"C\", " + 
                    " \"U2AZ5JP2gp8F6db\" : \"TR\", " + 
                    " \"b8BUkbw\" : \"wzQM\", " + 
                    " \"vwGtcWEZmJMj\" : \"vrCAliFs1Mg\" " + 
                    " }, " + 
                    " \"country_code\" : { " + 
                    " \"jEgUY\" : \"Ho16Dp9VF0Q1\", " + 
                    " \"QciIW6rJiTOK\" : \"1u6Cc77EWt7lzHP\", " + 
                    " \"l3XY9YklwKH\" : \"3oXjats\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"brand_name\" : \"\" " + 
                    " } " + 
                    " }, " + 
                    " \"giropay\" : { " + 
                    " \"name\" : { " + 
                    " \"HShkPdtt9\" : \"7yk\" " + 
                    " }, " + 
                    " \"country_code\" : { " + 
                    " \"j_d_Yvdp0\" : \"pn5KfULdNGvEcJMX\", " + 
                    " \"8iTrGlgcUA\" : \"VSaaEQG\", " + 
                    " \"MJj4\" : \"ku\", " + 
                    " \"3E6Bzq\" : \"\", " + 
                    " \"I2OVbWImj5hI0E\" : \"f1RrKJ3MfpNM\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"brand_name\" : \"茟\", " + 
                    " \"cancel_url\" : \"https://example.com/cancelUrl\" " + 
                    " } " + 
                    " }, " + 
                    " \"ideal\" : { " + 
                    " \"name\" : { " + 
                    " \"Cq8oEfsCyT_Ah\" : \"7_7LFI77k\", " + 
                    " \"ZE4JeKr3Kyq0b69d\" : \"e7Mrai8goyWyY\", " + 
                    " \"muI18wdjhK\" : \"4xH0BofazcHH85\", " + 
                    " \"c19HhAt\" : \"1\" " + 
                    " }, " + 
                    " \"country_code\" : { " + 
                    " \"XKdCWGCUU3lWkWzu\" : \"_vZR8h\", " + 
                    " \"Ow7hnpy_3\" : \"R2rDrieWZDReF\", " + 
                    " \"gf_7onIHE\" : \"6HToTv\", " + 
                    " \"oTv55Cs5Ia\" : \"ELcPCgoebDMIfn4\", " + 
                    " \"CKVUwt0UdKjZ\" : \"kBvhnd34\" " + 
                    " } " + 
                    " }, " + 
                    " \"mybank\" : { " + 
                    " \"name\" : { }, " + 
                    " \"country_code\" : { " + 
                    " \"U97oJc3ECzu7VOdI\" : \"WtCYNy\", " + 
                    " \"4g\" : \"VWz4GWc2\", " + 
                    " \"Zhj44AjvXMmpIQ\" : \"MzRd\", " + 
                    " \"5FYzP\" : \"yOS\" " + 
                    " } " + 
                    " }, " + 
                    " \"p24\" : { " + 
                    " \"name\" : { " + 
                    " \"AYO0mt1dv\" : \"\" " + 
                    " }, " + 
                    " \"email\" : { " + 
                    " \"5ygzm96ApPkplNIe\" : \"xWq8Tm\", " + 
                    " \"LQH\" : \"kOSJBtqoKf7W\" " + 
                    " }, " + 
                    " \"country_code\" : { " + 
                    " \"Jyxr\" : \"klFMWvAAHb9aCS\", " + 
                    " \"MH6S41On5t\" : \"NXfmLEcViB9QFOWJ\", " + 
                    " \"oz2QPX26da_vAAFx\" : \"gnoTb\" " + 
                    " } " + 
                    " }, " + 
                    " \"apple_pay\" : { " + 
                    " \"id\" : \"䛪\", " + 
                    " \"name\" : { " + 
                    " \"8ozAO870\" : \"ZiByg\", " + 
                    " \"DvsLmft377m0\" : \"tTmaxaNI\", " + 
                    " \"VMtoTf56jk5g5w\" : \"hm0T0Anue\", " + 
                    " \"IRF89\" : \"R7H9QiWU6ahjm\" " + 
                    " }, " + 
                    " \"phone_number\" : { " + 
                    " \"national_number\" : \"4\" " + 
                    " }, " + 
                    " \"decrypted_token\" : { " + 
                    " \"tokenized_card\" : { " + 
                    " \"name\" : \"䝔\", " + 
                    " \"number\" : \"306103883786064\", " + 
                    " \"security_code\" : \"530\", " + 
                    " \"last_digits\" : \"35\", " + 
                    " \"card_type\" : { }, " + 
                    " \"type\" : { }, " + 
                    " \"attributes\" : { " + 
                    " \"bYBXm41wBbDZ\" : \"aRb\", " + 
                    " \"PdWv21mO58\" : \"RCj\", " + 
                    " \"wUmUjCuD1ZPCWtL\" : \"j5PjNtopCfFeI\" " + 
                    " } " + 
                    " }, " + 
                    " \"device_manufacturer_id\" : \"\", " + 
                    " \"payment_data_type\" : \"EMV\" " + 
                    " }, " + 
                    " \"stored_credential\" : { " + 
                    " \"payment_initiator\" : \"MERCHANT\", " + 
                    " \"payment_type\" : \"EVOMASTER\", " + 
                    " \"usage\" : \"SUBSEQUENT\" " + 
                    " }, " + 
                    " \"vault_id\" : { " + 
                    " \"HLKXB3r21JH9r2Wm\" : \"MnoYnQGz\", " + 
                    " \"cH\" : \"fxDUwixzSYBKL_\" " + 
                    " }, " + 
                    " \"experience_context\" : { " + 
                    " \"return_url\" : \"https://www.example.com/returnURL\", " + 
                    " \"cancel_url\" : \"https://www.example.com/cancelURL\" " + 
                    " } " + 
                    " }, " + 
                    " \"venmo\" : { " + 
                    " \"vault_id\" : { }, " + 
                    " \"email_address\" : { " + 
                    " \"Ufn7o9YbRa3q\" : \"DvdW8Q\" " + 
                    " } " + 
                    " } " + 
                    " } " + 
                    " } ")
                .post(baseUrlOfSut + "/v2/checkout/orders/5O190127TN364715T/authorize")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("INVALID_REQUEST"))
                .body("'details'.size()", equalTo(1))
                .body("'details'[0].'field'", containsString("prefer"))
                .body("'details'[0].'value'", containsString("-l"))
                .body("'details'[0].'location'", containsString("header"))
                .body("'details'[0].'issue'", containsString("INVALID_PARAMETER_VALUE"))
                .body("'details'[0].'description'", containsString("The value of a field is invalid."))
                .body("'message'", containsString("Request is not well-formed, syntactically incorrect, or violates schema."))
                .body("'debug_id'", containsString("f136534a2bc96"))
                .body("'links'.size()", equalTo(1))
                .body("'links'[0].'href'", containsString("https://developer.paypal.com/api/rest/reference/orders/v2/errors/#INVALID_PARAMETER_VALUE"))
                .body("'links'[0].'rel'", containsString("information_link"))
                .body("'links'[0].'method'", containsString("GET"));
    }
    
    
    /**
    * Calls:
    * (404) POST:/v2/checkout/orders/{id}/confirm-payment-source
    */
    @Test(timeout = 60000)
    public void test_11_postOnConfirm_payment_sourceReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .header("PayPal-Client-Metadata-Id", "T")
                .contentType("application/json")
                .post(baseUrlOfSut + "/v2/checkout/orders/L2V/confirm-payment-source")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("RESOURCE_NOT_FOUND"))
                .body("'details'.size()", equalTo(1))
                .body("'details'[0].'issue'", containsString("INVALID_RESOURCE_ID"))
                .body("'details'[0].'description'", containsString("Specified resource ID does not exist. Please check the resource ID and try again."))
                .body("'message'", containsString("The specified resource does not exist."))
                .body("'debug_id'", containsString("f7590201bcc10"))
                .body("'links'.size()", equalTo(1))
                .body("'links'[0].'href'", containsString("https://developer.paypal.com/api/rest/reference/orders/v2/errors/#INVALID_RESOURCE_ID"))
                .body("'links'[0].'rel'", containsString("information_link"))
                .body("'links'[0].'method'", containsString("GET"));
    }
    
    
    /**
    * Calls:
    * (404) POST:/v2/checkout/orders/{id}/authorize
    * Using 3 examples:
    *   (authorize_422_payer_action_required_cib_psd2_sca_ba_in_sc) BODY -> {}
    *   (authorize_422_payer_action_required_cib_psd2_sca_ba_in_sc) HEADER: PayPal-Request-Id -> 7b92603e-77ed-4896-8e78-5dea2050476a
    *   (authorize_422_payer_action_required_cib_psd2_sca_ba_in_sc) PATH: id -> 9SY02093A2309081P
    */
    @Test(timeout = 60000)
    public void test_12_postOnAuthorizeReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .header("PayPal-Request-Id", "7b92603e-77ed-4896-8e78-5dea2050476a")
                .contentType("application/json")
                .body(" { } ")
                .post(baseUrlOfSut + "/v2/checkout/orders/9SY02093A2309081P/authorize")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("RESOURCE_NOT_FOUND"))
                .body("'details'.size()", equalTo(1))
                .body("'details'[0].'field'", containsString("order_id"))
                .body("'details'[0].'value'", containsString("9SY02093A2309081P"))
                .body("'details'[0].'location'", containsString("path"))
                .body("'details'[0].'issue'", containsString("INVALID_RESOURCE_ID"))
                .body("'details'[0].'description'", containsString("Specified resource ID does not exist. Please check the resource ID and try again."))
                .body("'message'", containsString("The specified resource does not exist."))
                .body("'debug_id'", containsString("f5277794a895b"))
                .body("'links'.size()", equalTo(1))
                .body("'links'[0].'href'", containsString("https://developer.paypal.com/api/rest/reference/orders/v2/errors/#INVALID_RESOURCE_ID"))
                .body("'links'[0].'rel'", containsString("information_link"))
                .body("'links'[0].'method'", containsString("GET"));
    }
    
    
    /**
    * Calls:
    * (404) OPTIONS:/v2/checkout/orders/{id}/confirm-payment-source
    */
    @Test(timeout = 60000)
    public void test_13_optionsOnConfirm_payment_sourceReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .options(baseUrlOfSut + "/v2/checkout/orders/R4Y/confirm-payment-source")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) OPTIONS:/v2/checkout/orders/{id}/authorize
    */
    @Test(timeout = 60000)
    public void test_14_optionsOnAuthorizeReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .options(baseUrlOfSut + "/v2/checkout/orders/644/authorize")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) OPTIONS:/v2/checkout/orders/{id}/capture
    */
    @Test(timeout = 60000)
    public void test_15_optionsOnCaptureReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .options(baseUrlOfSut + "/v2/checkout/orders/VO/capture")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) OPTIONS:/v2/checkout/orders/{id}/track
    */
    @Test(timeout = 60000)
    public void test_16_optionsOnTrackReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .options(baseUrlOfSut + "/v2/checkout/orders/76/track")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) OPTIONS:/v2/checkout/orders/{id}/trackers/{tracker_id}
    */
    @Test(timeout = 60000)
    public void test_17_optionsOnTrackerReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer A21AAKepjPkgaMKYKWrIUdJ6YDVQPnr2gdU3R6-J01uYGOdIUs6aEtCgAVrsrAzUPogNvlU7FWrX0mL6DKQSr7Xdfkf0ThNDg") // Fixed Headers
                .options(baseUrlOfSut + "/v2/checkout/orders/X8/trackers/DOQ")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
