/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import  io.restassured.config.HttpClientConfig;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import  io.restassured.config.EncoderConfig;
import  io.restassured.http.ContentType;
import  org.hamcrest.Matchers;
import static org.hamcrest.Matchers.*;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-07-27T21:37:59.110144941-03:00[America/Argentina/Buenos_Aires]
 * <br>
*  The generated test suite contains 11 tests
 * <br>
*  Covered targets: 101
 * <br>
*  Used time: 0h 2m 18s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_faults_Test {

    
    private static String baseUrlOfSut = "https://books.googleapis.com";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .httpClient(HttpClientConfig.httpClientConfig()
                .setParam("http.socket.timeout", 30000)
                .setParam("http.connection.timeout", 30000))
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .encoderConfig(EncoderConfig.encoderConfig().encodeContentTypeAs("application/octet-stream", ContentType.TEXT));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (400) GET:/books/v1/volumes/mostRecent
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_0_getOnMostRecentReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/volumes/mostRecent'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/books/v1/volumes/mostRecent?" + 
                    "key=clcznfBYtZPw&" + 
                    "prettyPrint=false&" + 
                    "quotaUser=KnIS1yfnu")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'code'", numberMatches(400))
                .body("'error'.'message'", containsString("API key not valid. Please pass a valid API key."))
                .body("'error'.'errors'.size()", equalTo(1))
                .body("'error'.'errors'[0].'message'", containsString("API key not valid. Please pass a valid API key."))
                .body("'error'.'errors'[0].'domain'", containsString("global"))
                .body("'error'.'errors'[0].'reason'", containsString("badRequest"))
                .body("'error'.'status'", containsString("INVALID_ARGUMENT"))
                .body("'error'.'details'.size()", equalTo(2))
                .body("'error'.'details'[0].'@type'", containsString("type.googleapis.com/google.rpc.ErrorInfo"))
                .body("'error'.'details'[0].'reason'", containsString("API_KEY_INVALID"))
                .body("'error'.'details'[0].'domain'", containsString("googleapis.com"))
                .body("'error'.'details'[0].'metadata'.'service'", containsString("books.googleapis.com"))
                .body("'error'.'details'[1].'@type'", containsString("type.googleapis.com/google.rpc.LocalizedMessage"))
                .body("'error'.'details'[1].'locale'", containsString("en-US"))
                .body("'error'.'details'[1].'message'", containsString("API key not valid. Please pass a valid API key."));
    }
    
    
    /**
    * Calls:
    * (400) GET:/books/v1/volumes/{volumeId}
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_1_getOnVolumReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/volumes/{volumeId}'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/books/v1/volumes/FMefMcQxk?" + 
                    "key=9f4fkdLbYzq6hmgR&" + 
                    "country=_&" + 
                    "fields=maZsRZ4MIkVmt&" + 
                    "prettyPrint=true&" + 
                    "projection=EVOMASTER")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'code'", numberMatches(400))
                .body("'error'.'message'", containsString("API key not valid. Please pass a valid API key."))
                .body("'error'.'errors'.size()", equalTo(1))
                .body("'error'.'errors'[0].'message'", containsString("API key not valid. Please pass a valid API key."))
                .body("'error'.'errors'[0].'domain'", containsString("global"))
                .body("'error'.'errors'[0].'reason'", containsString("badRequest"))
                .body("'error'.'status'", containsString("INVALID_ARGUMENT"))
                .body("'error'.'details'.size()", equalTo(2))
                .body("'error'.'details'[0].'@type'", containsString("type.googleapis.com/google.rpc.ErrorInfo"))
                .body("'error'.'details'[0].'reason'", containsString("API_KEY_INVALID"))
                .body("'error'.'details'[0].'domain'", containsString("googleapis.com"))
                .body("'error'.'details'[0].'metadata'.'service'", containsString("books.googleapis.com"))
                .body("'error'.'details'[1].'@type'", containsString("type.googleapis.com/google.rpc.LocalizedMessage"))
                .body("'error'.'details'[1].'locale'", containsString("en-US"))
                .body("'error'.'details'[1].'message'", containsString("API key not valid. Please pass a valid API key."));
    }
    
    
    /**
    * Calls:
    * (401) GET:/books/v1/mylibrary/bookshelves
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_2_getOnMylibraryBookshelvesWithQueryParamsPrettyPrintReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/mylibrary/bookshelves'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/books/v1/mylibrary/bookshelves?" + 
                    "key=2n&" + 
                    "fields=oL7zPSoFdVNP&" + 
                    "prettyPrint=true&" + 
                    "source=IWCK")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Bearer realm=\"https://accounts.google.com/\"")
                .contentType("application/json")
                .body("'error'.'code'", numberMatches(401))
                .body("'error'.'message'", containsString("API keys are not supported by this API. Expected OAuth2 access token or other authentication credentials that assert a principal. See https://cloud.google.com/docs/authentication"))
                .body("'error'.'errors'.size()", equalTo(1))
                .body("'error'.'errors'[0].'message'", containsString("Login Required."))
                .body("'error'.'errors'[0].'domain'", containsString("global"))
                .body("'error'.'errors'[0].'reason'", containsString("required"))
                .body("'error'.'errors'[0].'location'", containsString("Authorization"))
                .body("'error'.'errors'[0].'locationType'", containsString("header"))
                .body("'error'.'status'", containsString("UNAUTHENTICATED"))
                .body("'error'.'details'.size()", equalTo(1))
                .body("'error'.'details'[0].'@type'", containsString("type.googleapis.com/google.rpc.ErrorInfo"))
                .body("'error'.'details'[0].'reason'", containsString("CREDENTIALS_MISSING"))
                .body("'error'.'details'[0].'domain'", containsString("googleapis.com"))
                .body("'error'.'details'[0].'metadata'.'method'", containsString("books.api.proto.frontend.v1.BooksMylibraryBookshelves.List"))
                .body("'error'.'details'[0].'metadata'.'service'", containsString("books.googleapis.com"));
    }
    
    
    /**
    * Calls:
    * (400) GET:/books/v1/users/{userId}/bookshelves
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_3_getOnUserBookshelvesWithQueryParamReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/users/{userId}/bookshelves'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/books/v1/users/KiZtbYP3/bookshelves?key=AIzaSyDAsbskr6J6Q5nCzrN9-SoqW0gCWzCoWZw")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'code'", numberMatches(400))
                .body("'error'.'message'", containsString("Invalid user ID."))
                .body("'error'.'errors'.size()", equalTo(1))
                .body("'error'.'errors'[0].'message'", containsString("Invalid user ID."))
                .body("'error'.'errors'[0].'domain'", containsString("global"))
                .body("'error'.'errors'[0].'reason'", containsString("invalidUser"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/books/v1/mylibrary/bookshelves/{shelf}
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_4_getOnMylibraryBookshelvWithQueryParamsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/mylibrary/bookshelves/{shelf}'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/books/v1/mylibrary/bookshelves/s9tnTxAhPrHRsl0?" + 
                    "key=Pnv7aSUeeC7I&" + 
                    "fields=qw9OZjXxxi9&" + 
                    "source=ME5t2b")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Bearer realm=\"https://accounts.google.com/\"")
                .contentType("application/json")
                .body("'error'.'code'", numberMatches(401))
                .body("'error'.'message'", containsString("API keys are not supported by this API. Expected OAuth2 access token or other authentication credentials that assert a principal. See https://cloud.google.com/docs/authentication"))
                .body("'error'.'errors'.size()", equalTo(1))
                .body("'error'.'errors'[0].'message'", containsString("Login Required."))
                .body("'error'.'errors'[0].'domain'", containsString("global"))
                .body("'error'.'errors'[0].'reason'", containsString("required"))
                .body("'error'.'errors'[0].'location'", containsString("Authorization"))
                .body("'error'.'errors'[0].'locationType'", containsString("header"))
                .body("'error'.'status'", containsString("UNAUTHENTICATED"))
                .body("'error'.'details'.size()", equalTo(1))
                .body("'error'.'details'[0].'@type'", containsString("type.googleapis.com/google.rpc.ErrorInfo"))
                .body("'error'.'details'[0].'reason'", containsString("CREDENTIALS_MISSING"))
                .body("'error'.'details'[0].'domain'", containsString("googleapis.com"))
                .body("'error'.'details'[0].'metadata'.'method'", containsString("books.api.proto.frontend.v1.BooksMylibraryBookshelves.Get"))
                .body("'error'.'details'[0].'metadata'.'service'", containsString("books.googleapis.com"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/books/v1/volumes/{volumeId}/reviews
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_5_getOnReviewsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/volumes/{volumeId}/reviews'.
        given().accept("*/*")
                .get(baseUrlOfSut + "/books/v1/volumes/BGUS8/reviews?" + 
                    "key=_atJRIrSa3Pt4Gk&" + 
                    "fields=m8kpXH&" + 
                    "prettyPrint=false&" + 
                    "startIndex=164")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (400) GET:/books/v1/users/{userId}/bookshelves/{shelf}
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_6_getOnUserBookshelvWithQueryParamsPrettyPrintEmptySourceReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/users/{userId}/bookshelves/{shelf}'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/books/v1/users/SMD_TDBMMwa/bookshelves/4P_?" + 
                    "key=IdHiuCsFI7V5gw&" + 
                    "fields=Q&" + 
                    "prettyPrint=true&" + 
                    "source=")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'code'", numberMatches(400))
                .body("'error'.'message'", containsString("API key not valid. Please pass a valid API key."))
                .body("'error'.'errors'.size()", equalTo(1))
                .body("'error'.'errors'[0].'message'", containsString("API key not valid. Please pass a valid API key."))
                .body("'error'.'errors'[0].'domain'", containsString("global"))
                .body("'error'.'errors'[0].'reason'", containsString("badRequest"))
                .body("'error'.'status'", containsString("INVALID_ARGUMENT"))
                .body("'error'.'details'.size()", equalTo(2))
                .body("'error'.'details'[0].'@type'", containsString("type.googleapis.com/google.rpc.ErrorInfo"))
                .body("'error'.'details'[0].'reason'", containsString("API_KEY_INVALID"))
                .body("'error'.'details'[0].'domain'", containsString("googleapis.com"))
                .body("'error'.'details'[0].'metadata'.'service'", containsString("books.googleapis.com"))
                .body("'error'.'details'[1].'@type'", containsString("type.googleapis.com/google.rpc.LocalizedMessage"))
                .body("'error'.'details'[1].'locale'", containsString("en-US"))
                .body("'error'.'details'[1].'message'", containsString("API key not valid. Please pass a valid API key."));
    }
    
    
    /**
    * Calls:
    * (401) GET:/books/v1/mylibrary/bookshelves/{shelf}/volumes
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_7_getOnVolumesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/mylibrary/bookshelves/{shelf}/volumes'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/books/v1/mylibrary/bookshelves/wKdU6ZIBpmY/volumes?" + 
                    "key=qC8i&" + 
                    "fields=P&" + 
                    "prettyPrint=false&" + 
                    "maxResults=335&" + 
                    "q=B&" + 
                    "source=RWyOX1&" + 
                    "startIndex=1585264801")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Bearer realm=\"https://accounts.google.com/\"")
                .contentType("application/json")
                .body("'error'.'code'", numberMatches(401))
                .body("'error'.'message'", containsString("API keys are not supported by this API. Expected OAuth2 access token or other authentication credentials that assert a principal. See https://cloud.google.com/docs/authentication"))
                .body("'error'.'errors'.size()", equalTo(1))
                .body("'error'.'errors'[0].'message'", containsString("Login Required."))
                .body("'error'.'errors'[0].'domain'", containsString("global"))
                .body("'error'.'errors'[0].'reason'", containsString("required"))
                .body("'error'.'errors'[0].'location'", containsString("Authorization"))
                .body("'error'.'errors'[0].'locationType'", containsString("header"))
                .body("'error'.'status'", containsString("UNAUTHENTICATED"))
                .body("'error'.'details'.size()", equalTo(1))
                .body("'error'.'details'[0].'@type'", containsString("type.googleapis.com/google.rpc.ErrorInfo"))
                .body("'error'.'details'[0].'reason'", containsString("CREDENTIALS_MISSING"))
                .body("'error'.'details'[0].'domain'", containsString("googleapis.com"))
                .body("'error'.'details'[0].'metadata'.'method'", containsString("books.api.proto.frontend.v1.BooksMylibraryBookshelvesVolumes.List"))
                .body("'error'.'details'[0].'metadata'.'service'", containsString("books.googleapis.com"));
    }
    
    
    /**
    * Calls:
    * (411) POST:/books/v1/mylibrary/bookshelves/{shelf}/removeVolume
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_8_postOnRemoveVolumeReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 411 not defined for path '/mylibrary/bookshelves/{shelf}/removeVolume'.
        given().accept("*/*")
                .noContentType()
                .post(baseUrlOfSut + "/books/v1/mylibrary/bookshelves/RomAsOc_BvS/removeVolume?" + 
                    "key=202C3L8&" + 
                    "volumeId=zlUHnEH&" + 
                    "source=se7kvXry2O7bs")
                .then()
                .statusCode(411)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (411) POST:/books/v1/mylibrary/bookshelves/{shelf}/addVolume
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_9_postOnAddVolumeReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 411 not defined for path '/mylibrary/bookshelves/{shelf}/addVolume'.
        given().accept("*/*")
                .noContentType()
                .post(baseUrlOfSut + "/books/v1/mylibrary/bookshelves/xxzhdmYsI7H3/addVolume?" + 
                    "key=_LJhHJYkcZ_jKA&" + 
                    "volumeId=x4l&" + 
                    "reason=7lmB&" + 
                    "source=VcjtqBc4S")
                .then()
                .statusCode(411)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (400) GET:/books/v1/users/{userId}/bookshelves/{shelf}/volumes
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_10_getOnVolumesReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/users/{userId}/bookshelves/{shelf}/volumes'.
        given().accept("application/json")
                .get(baseUrlOfSut + "/books/v1/users/0uC47zAYHntstZ/bookshelves/jnqkRn9FK3/volumes?" + 
                    "key=5_jOfDYm4TlfRpe&" + 
                    "fields=OwLfiV7eKz&" + 
                    "prettyPrint=false&" + 
                    "source=j_AdLu0FI7y")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'code'", numberMatches(400))
                .body("'error'.'message'", containsString("API key not valid. Please pass a valid API key."))
                .body("'error'.'errors'.size()", equalTo(1))
                .body("'error'.'errors'[0].'message'", containsString("API key not valid. Please pass a valid API key."))
                .body("'error'.'errors'[0].'domain'", containsString("global"))
                .body("'error'.'errors'[0].'reason'", containsString("badRequest"))
                .body("'error'.'status'", containsString("INVALID_ARGUMENT"))
                .body("'error'.'details'.size()", equalTo(2))
                .body("'error'.'details'[0].'@type'", containsString("type.googleapis.com/google.rpc.ErrorInfo"))
                .body("'error'.'details'[0].'reason'", containsString("API_KEY_INVALID"))
                .body("'error'.'details'[0].'domain'", containsString("googleapis.com"))
                .body("'error'.'details'[0].'metadata'.'service'", containsString("books.googleapis.com"))
                .body("'error'.'details'[1].'@type'", containsString("type.googleapis.com/google.rpc.LocalizedMessage"))
                .body("'error'.'details'[1].'locale'", containsString("en-US"))
                .body("'error'.'details'[1].'message'", containsString("API key not valid. Please pass a valid API key."));
    }


}
