#!/usr/bin/env python

# LICENSE DISCLAIMER
# This file has been generated by EvoMaster.
# The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
# This generated software (i.e., the test suite in this file) can be freely used, modified, 
# and distributed as you see fit without any restrictions.
import json
import unittest
import requests
import time
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *
EM_HTTP_TIMEOUT_S = 30.0


#  This file was automatically generated by EvoMaster on 2026-08-13T09:10:20.409657107-03:00[America/Argentina/Buenos_Aires]
#  
#  The generated test suite contains 67 tests
#  
#  Covered targets: 465
#  
#  Used time: 0h 10m 42s
#  
#  Needed budget for current results: 100%
#  
#  This file contains test cases that are likely to indicate faults.
#  
class EvoMaster_faults_Test(unittest.TestCase):

    
    baseUrlOfSut = "https://api.themoviedb.org"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (401) POST:/3/list
    # Found 1 potential fault of type-code 101
    # Using 1 example:
    #   (Request Example) BODY -> {"RAW_BODY":"4uCTj3CgZQ_97g72"}
    @timeout_decorator.timeout(60)
    def test_0_post_on_list_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/list'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"RAW_BODY\" : \"4uCTj3CgZQ_97g72\" " + \
            " } "
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/list?session_id=U",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (400) GET:/3/tv/top_rated
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_1_get_on_top_rated_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/tv/top_rated'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/top_rated?page=613",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 22
        assert res_0.json()["status_message"] == "Invalid page: Pages start at 1 and max at 500. They are expected to be an integer."
    
    
    # Calls:
    # (400) GET:/3/movie/now_playing
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_2_get_on_now_playing_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/movie/now_playing'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/movie/now_playing?" + 
                    "page=859&" + 
                    "region=N2Tc6uiZHkdG",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 22
        assert res_0.json()["status_message"] == "Invalid page: Pages start at 1 and max at 500. They are expected to be an integer."
    
    
    # Calls:
    # (400) GET:/3/person/changes
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_3_get_on_changes_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/person/changes'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/person/changes?" + 
                    "page=399&" + 
                    "start_date=1928-08-17",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 51
        assert res_0.json()["status_message"] == "Invalid start date: The first change record in our database wasn't created until 2012-10-05."
    
    
    # Calls:
    # (400) GET:/3/movie/changes
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_4_get_on_movie_changes_with_queryParams_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/movie/changes'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/movie/changes?" + 
                    "page=786&" + 
                    "start_date=1944-01-25",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 22
        assert res_0.json()["status_message"] == "Invalid page: Pages start at 1 and max at 500. They are expected to be an integer."
    
    
    # Calls:
    # (400) DELETE:/3/authentication/session
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_5_delete_on_session_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/authentication/session'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"RAW_BODY\" : \"dPln89wBcHgbH\" " + \
            " } "
        headers['Accept'] = "application/json"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/3/authentication/session",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 5
        assert res_0.json()["status_message"] == "Invalid parameters: Your request parameters are incorrect."
    
    
    # Calls:
    # (401) GET:/3/account/{account_id}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_6_get_on_account_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/account/{account_id}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/account/195?session_id=1V0xqdmMPM3pa",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) DELETE:/3/list/{list_id}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_7_delete_on_list_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/list/{list_id}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/3/list/427?session_id=nX7ct",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (404) GET:/3/review/{review_id}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_8_get_on_review_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/review/{review_id}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/review/XJ",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/movie/{movie_id}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_9_get_on__3_movi_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/movie/{movie_id}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/movie/10",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/list/{list_id}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_10_get_on_list_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/list/{list_id}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/list/924?language=iCTBJ2h3n",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/keyword/{keyword_id}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_11_get_on_keyword_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/keyword/{keyword_id}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/keyword/735",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/credit/{credit_id}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_12_get_on_credit_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/credit/{credit_id}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/credit/y",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/collection/{collection_id}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_13_get_on_collect_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/collection/{collection_id}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/collection/96?language=uvPVJQjE03icU3Ps",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (400) GET:/3/tv/{series_id}/changes
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_14_get_on_tv_changes_with_queryParams_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/tv/{series_id}/changes'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/225/changes?" + 
                    "end_date=DT&" + 
                    "page=508588629",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 22
        assert res_0.json()["status_message"] == "Invalid page: Pages start at 1 and max at 500. They are expected to be an integer."
    
    
    # Calls:
    # (400) GET:/3/trending/movie/{time_window}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_15_get_on_trending_movi_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/trending/movie/{time_window}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/trending/movie/EVOMASTER",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 5
        assert res_0.json()["status_message"] == "Invalid parameters: Your request parameters are incorrect."
    
    
    # Calls:
    # (400) GET:/3/movie/{movie_id}/changes
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_16_get_on_movi_changes_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/movie/{movie_id}/changes'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/movie/360/changes?end_date=1904-12-22",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 51
        assert res_0.json()["status_message"] == "Invalid start date: The first change record in our database wasn't created until 2012-10-05."
    
    
    # Calls:
    # (400) GET:/3/keyword/{keyword_id}/movies
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_17_get_on_keyword_movies_with_queryParams_include_adult_negative_page_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/keyword/{keyword_id}/movies'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/keyword/h/movies?" + 
                    "include_adult=true&" + 
                    "language=PFUo36Wsj&" + 
                    "page=-1762957078",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 22
        assert res_0.json()["status_message"] == "Invalid page: Pages start at 1 and max at 500. They are expected to be an integer."
    
    
    # Calls:
    # (400) POST:/3/tv/{series_id}/rating
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_18_post_on_tv_rating_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/tv/{series_id}/rating'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["Content-Type"] = "WR2J"
        headers["content-type"] = "application/json"
        body = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/tv/25/rating",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 5
        assert res_0.json()["status_message"] == "Invalid parameters: Your request parameters are incorrect."
    
    
    # Calls:
    # (400) POST:/3/movie/{movie_id}/rating
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_19_post_on_movi_rating_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/movie/{movie_id}/rating'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["Content-Type"] = ""
        headers["content-type"] = "application/json"
        body = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/movie/369/rating",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 5
        assert res_0.json()["status_message"] == "Invalid parameters: Your request parameters are incorrect."
    
    
    # Calls:
    # (400) POST:/3/authentication/token/validate_with_login
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_20_post_on_validate_with_login_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/authentication/token/validate_with_login'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"RAW_BODY\" : \"cN\" " + \
            " } "
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/authentication/token/validate_with_login",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 5
        assert res_0.json()["status_message"] == "Invalid parameters: Your request parameters are incorrect."
    
    
    # Calls:
    # (400) POST:/3/account/{account_id}/favorite
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_21_post_on_favorite_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/account/{account_id}/favorite'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["content-type"] = "application/json"
        body = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/account/252/favorite",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 5
        assert res_0.json()["status_message"] == "Invalid parameters: Your request parameters are incorrect."
    
    
    # Calls:
    # (401) GET:/3/movie/{movie_id}/account_states
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_22_get_on_movi_account_states_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/movie/{movie_id}/account_states'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/movie/489/account_states?session_id=6qOvO8OlLhtv3",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) POST:/3/list/{list_id}/remove_item
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_23_post_on_remove_item_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/list/{list_id}/remove_item'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["content-type"] = "application/json"
        body = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/list/829/remove_item?session_id=Hx52W3",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) POST:/3/list/{list_id}/clear
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_24_post_on_clear_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/list/{list_id}/clear'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/list/629/clear?" + 
                    "session_id=NfZ1et&" + 
                    "confirm=false",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) POST:/3/list/{list_id}/add_item
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_25_post_on_add_item_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/list/{list_id}/add_item'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["content-type"] = "application/json"
        body = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/list/608/add_item?session_id=UijtCdVY",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) POST:/3/account/{account_id}/watchlist
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_26_post_on_watchlist_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/account/{account_id}/watchlist'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["content-type"] = "application/json"
        body = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/account/546/watchlist?session_id=Eo",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) DELETE:/3/tv/{series_id}/rating
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_27_delete_on_tv_rating_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/tv/{series_id}/rating'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/3/tv/519/rating?session_id=35KeOd1AKSFrTB_r",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) DELETE:/3/movie/{movie_id}/rating
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_28_delete_on_movi_rating_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/movie/{movie_id}/rating'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/3/movie/593/rating?session_id=Xaj",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (404) GET:/3/tv/episode_group/{tv_episode_group_id}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_29_get_on_episode_group_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/episode_group/{tv_episode_group_id}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/episode_group/H",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/similar
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_30_get_on_similar_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/similar'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/OB31/similar",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 6
        assert res_0.json()["status_message"] == "Invalid id: The pre-requisite id is invalid or not found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/external_ids
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_31_get_on_tv_external_ids_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/external_ids'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/986/external_ids",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/person/{person_id}/tagged_images
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_32_get_on_tagged_images_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/person/{person_id}/tagged_images'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/person/-172489270/tagged_images",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 6
        assert res_0.json()["status_message"] == "Invalid id: The pre-requisite id is invalid or not found."
    
    
    # Calls:
    # (404) GET:/3/person/{person_id}/combined_credits
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_33_get_on_combined_credits_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/person/{person_id}/combined_credits'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/person/L2i5AMj2Dw_mPJ0/combined_credits?language=tcO1BjpihJtQBiE",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 6
        assert res_0.json()["status_message"] == "Invalid id: The pre-requisite id is invalid or not found."
    
    
    # Calls:
    # (404) GET:/3/movie/{movie_id}/recommendations
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_34_get_on_recommendations_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/movie/{movie_id}/recommendations'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/movie/46/recommendations",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/movie/{movie_id}/keywords
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_35_get_on_keywords_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/movie/{movie_id}/keywords'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/movie/Gd58tVTy/keywords",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 6
        assert res_0.json()["status_message"] == "Invalid id: The pre-requisite id is invalid or not found."
    
    
    # Calls:
    # (404) GET:/3/list/{list_id}/item_status
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_36_get_on_item_status_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/list/{list_id}/item_status'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/list/995684665/item_status",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/collection/{collection_id}/translations
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_37_get_on_collect_translations_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/collection/{collection_id}/translations'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/collection/667/translations",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/collection/{collection_id}/images
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_38_get_on_collect_images_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/collection/{collection_id}/images'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/collection/451/images?include_image_language=CjNM",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) POST:/3/authentication/session/new
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_39_post_on_new_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/authentication/session/new'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"RAW_BODY\" : \"cAz\" " + \
            " } "
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/authentication/session/new",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (422) GET:/3/person/{person_id}/changes
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_40_get_on_changes_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 422 not defined for path '/3/person/{person_id}/changes'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/person/572/changes?" + 
                    "end_date=2098-01-19&" + 
                    "page=132&" + 
                    "start_date=2066-04-18",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 422
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 20
        assert res_0.json()["status_message"] == "Invalid date range: Should be a range no longer than 14 days."
    
    
    # Calls:
    # (400) GET:/3/tv/season/{season_id}/changes
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_41_get_on_season_changes_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/tv/season/{season_id}/changes'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/season/161/changes?page=943",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 22
        assert res_0.json()["status_message"] == "Invalid page: Pages start at 1 and max at 500. They are expected to be an integer."
    
    
    # Calls:
    # (400) POST:/3/authentication/session/convert/4
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_42_post_on__4_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/authentication/session/convert/4'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["content-type"] = "application/json"
        body = {}
        body = " { " + \
            " \"RAW_BODY\" : \"gJZ1yYQnVv_zh6Y\" " + \
            " } "
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/authentication/session/convert/4",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 5
        assert res_0.json()["status_message"] == "Invalid parameters: Your request parameters are incorrect."
    
    
    # Calls:
    # (401) GET:/3/guest_session/{guest_session_id}/rated/tv
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_43_get_on_tv_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/guest_session/{guest_session_id}/rated/tv'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/guest_session/QxLn/rated/tv?" + 
                    "language=jhAwB3ijI&" + 
                    "sort_by=EVOMASTER",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) GET:/3/guest_session/{guest_session_id}/rated/movies
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_44_get_on_rated_movies_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/guest_session/{guest_session_id}/rated/movies'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/guest_session/db5qIeXdBw/rated/movies?sort_by=EVOMASTER",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) GET:/3/account/{account_id}/rated/movies
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_45_get_on_rated_movies_with_queryParams_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/account/{account_id}/rated/movies'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/account/24/rated/movies?" + 
                    "language=6DiUGqavQCjHgO&" + 
                    "session_id=kOLB5J15fr_r&" + 
                    "sort_by=EVOMASTER",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) GET:/3/account/{account_id}/favorite/movies
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_46_get_on_favorite_movies_with_queryParams_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/account/{account_id}/favorite/movies'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/account/831/favorite/movies?" + 
                    "language=th2I&" + 
                    "page=1&" + 
                    "session_id=qT2egq2Y1Nx&" + 
                    "sort_by=created_at.asc",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_47_get_on_season_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/551/season/405?append_to_response=pCipmj1MyQGee",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (400) GET:/3/guest_session/{guest_session_id}/rated/tv/episodes
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_48_get_on_episodes_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/guest_session/{guest_session_id}/rated/tv/episodes'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/guest_session/W7YVi0b7NB9/rated/tv/episodes?" + 
                    "language=8DUYGBUsqn&" + 
                    "page=717",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 22
        assert res_0.json()["status_message"] == "Invalid page: Pages start at 1 and max at 500. They are expected to be an integer."
    
    
    # Calls:
    # (400) GET:/3/account/{account_id}/rated/tv/episodes
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_49_get_on_episodes_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/3/account/{account_id}/rated/tv/episodes'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/account/46/rated/tv/episodes?" + 
                    "page=869&" + 
                    "session_id=RuviL_B",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 400
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 22
        assert res_0.json()["status_message"] == "Invalid page: Pages start at 1 and max at 500. They are expected to be an integer."
    
    
    # Calls:
    # (401) GET:/3/tv/{series_id}/season/{season_number}/account_states
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_50_get_on_season_account_states_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/tv/{series_id}/season/{season_number}/account_states'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/698/season/532/account_states?session_id=QGq",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/videos
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_51_get_on_season_videos_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/videos'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/944/season/30/videos",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/translations
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_52_get_on_season_translations_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/translations'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/169/season/440/translations",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/images
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_53_get_on_season_images_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/images'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/371/season/978/images?language=n",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/external_ids
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_54_get_on_season_external_ids_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/external_ids'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/223/season/560/external_ids",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/credits
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_55_get_on_season_credits_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/credits'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/32/season/472/credits?language=en-US",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/aggregate_credits
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_56_get_on_aggregate_credits_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/aggregate_credits'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/863/season/403/aggregate_credits?language=eZ7npyD",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/episode/{episode_number}
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_57_get_on_episod_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/-665772343/season/20/episode/335",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 6
        assert res_0.json()["status_message"] == "Invalid id: The pre-requisite id is invalid or not found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/watch/providers
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_58_get_on_providers_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/watch/providers'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/577/season/631/watch/providers?language=9IeSV7PTC",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (401) GET:/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/account_states
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_59_get_on_episod_account_states_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/account_states'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/463/season/996/episode/817/account_states?session_id=eV",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) POST:/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/rating
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_60_post_on_episod_rating_with_queryParams_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/rating'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["Content-Type"] = "LOBkP5O3U"
        headers["content-type"] = "application/json"
        body = {}
        headers['Accept'] = "application/json"
        res_0 = requests \
                .post(self.baseUrlOfSut + "/3/tv/222/season/427/episode/74/rating?" + 
                    "guest_session_id=R44TryXWxx21l0&" + 
                    "session_id=gQyIOvvEPoYHb82",
                    headers=headers, data=body, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (401) DELETE:/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/rating
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_61_delete_on_episod_rating_with_queryParams_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/rating'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers["Content-Type"] = "w"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .delete(self.baseUrlOfSut + "/3/tv/399/season/463/episode/757/rating?" + 
                    "guest_session_id=9X79QSlRKe09&" + 
                    "session_id=NiZ36kFhb",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 401
        assert "www-authenticate" not in res_0.headers
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 3
        assert res_0.json()["status_message"] == "Authentication failed: You do not have permissions to access the service."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/videos
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_62_get_on_episod_videos_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/videos'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/994/season/393/episode/1464533344/videos?include_video_language=s",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/translations
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_63_get_on_episod_translations_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/translations'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/893/season/624/episode/274/translations",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/images
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_64_get_on_episod_images_with_queryParam_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/images'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/223/season/528/episode/781/images?include_image_language=mcailF8QSR",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/external_ids
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_65_get_on_episod_external_ids_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/external_ids'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/829/season/499/episode/r7/external_ids",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 6
        assert res_0.json()["status_message"] == "Invalid id: The pre-requisite id is invalid or not found."
    
    
    # Calls:
    # (404) GET:/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/credits
    # Found 1 potential fault of type-code 101
    @timeout_decorator.timeout(60)
    def test_66_get_on_episod_credits_returnsMismatchResponseWithSchema(self):
        
        # Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/3/tv/{series_id}/season/{season_number}/episode/{episode_number}/credits'.
        headers = {}
        headers["Authorization"] = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZWViOGU5YzQ1NTUwOTQ1MGJkMGRhMWM0M2U2NTFiNyIsIm5iZiI6MTc4NTI4NTU4Ny4xNDcsInN1YiI6IjZhNjk0YmQzNjA5MjU3MTljMjc4Y2VkZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1UfOReeDArAIHzWHS7elG4a_He6XPw14extJpp6G0PQ"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/3/tv/865668198/season/1415708422/episode/93/credits",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["success"] == False
        assert res_0.json()["status_code"] == 34
        assert res_0.json()["status_message"] == "The resource you requested could not be found."


if __name__ == '__main__':
    unittest.main()
