/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import  io.restassured.config.HttpClientConfig;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import  io.restassured.config.EncoderConfig;
import  io.restassured.http.ContentType;
import  org.hamcrest.Matchers;
import static org.hamcrest.Matchers.*;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-07-27T21:35:15.800456771-03:00[America/Argentina/Buenos_Aires]
 * <br>
*  The generated test suite contains 4 tests
 * <br>
*  Covered targets: 19
 * <br>
*  Used time: 0h 2m 10s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_successes_Test {

    
    private static String baseUrlOfSut = "https://api.spotify.com";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .httpClient(HttpClientConfig.httpClientConfig()
                .setParam("http.socket.timeout", 30000)
                .setParam("http.connection.timeout", 30000))
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .encoderConfig(EncoderConfig.encoderConfig().encodeContentTypeAs("application/octet-stream", ContentType.TEXT));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (204) OPTIONS:/v1/albums
    */
    @Test(timeout = 60000)
    public void test_0_optionsOnAlbumsReturns204() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .options(baseUrlOfSut + "/v1/albums")
                .then()
                .statusCode(204)
                .assertThat()
                // .header("allow", "GET, HEAD, OPTIONS")
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) OPTIONS:/v1/albums/{id}
    */
    @Test(timeout = 60000)
    public void test_1_optionsOnAlbumReturns204() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .options(baseUrlOfSut + "/v1/albums/RM8zzJ")
                .then()
                .statusCode(204)
                .assertThat()
                // .header("allow", "GET, HEAD, OPTIONS")
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) OPTIONS:/v1/artists/{id}
    */
    @Test(timeout = 60000)
    public void test_2_optionsOnArtistReturns204() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .options(baseUrlOfSut + "/v1/artists/DvCOcQ")
                .then()
                .statusCode(204)
                .assertThat()
                // .header("allow", "GET, HEAD, OPTIONS")
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) OPTIONS:/v1/albums/{id}/tracks
    * Using 1 example:
    *   (-) PATH: id -> 4aawyAB9vmqN3uQ7FjRGTy
    */
    @Test(timeout = 60000)
    public void test_3_optionsOnTracksReturns204() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .options(baseUrlOfSut + "/v1/albums/4aawyAB9vmqN3uQ7FjRGTy/tracks")
                .then()
                .statusCode(204)
                .assertThat()
                // .header("allow", "GET, HEAD, OPTIONS")
                .body(isEmptyOrNullString());
    }


}
