/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import  io.restassured.config.HttpClientConfig;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import  io.restassured.config.EncoderConfig;
import  io.restassured.http.ContentType;
import  org.hamcrest.Matchers;
import static org.hamcrest.Matchers.*;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-07-27T21:35:15.816685884-03:00[America/Argentina/Buenos_Aires]
 * <br>
*  The generated test suite contains 31 tests
 * <br>
*  Covered targets: 211
 * <br>
*  Used time: 0h 2m 10s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_others_Test {

    
    private static String baseUrlOfSut = "https://api.spotify.com";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .httpClient(HttpClientConfig.httpClientConfig()
                .setParam("http.socket.timeout", 30000)
                .setParam("http.connection.timeout", 30000))
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .encoderConfig(EncoderConfig.encoderConfig().encodeContentTypeAs("application/octet-stream", ContentType.TEXT));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (403) GET:/v1/markets
    */
    @Test(timeout = 60000)
    public void test_0_getOnMarketsReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/markets")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Forbidden"));
    }
    
    
    /**
    * Calls:
    * (403) GET:/v1/audio-features
    */
    @Test(timeout = 60000)
    public void test_1_getOnAudio_featuresReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/audio-features?ids=JP__Waw")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v1/recommendations
    * Using 2 examples:
    *   (-) QUERY: seed_artists -> 4NHQUGzhtTLFvgF5SZesLK
    *   (-) QUERY: seed_tracks -> 0c6xIDDpzE81m2q797ordA
    */
    @Test(timeout = 60000)
    public void test_2_getOnRecommendationsReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/recommendations?" + 
                    "market=botpk&" + 
                    "seed_artists=4NHQUGzhtTLFvgF5SZesLK&" + 
                    "seed_genres=wcLoqJ9nAEly&" + 
                    "seed_tracks=0c6xIDDpzE81m2q797ordA&" + 
                    "max_acousticness=0.1899923400193092&" + 
                    "target_acousticness=0.4294757307326714&" + 
                    "min_danceability=0.052297878789476226&" + 
                    "min_duration_ms=185&" + 
                    "target_energy=0.25172246079600424&" + 
                    "target_instrumentalness=0.8896528845839449&" + 
                    "max_key=0&" + 
                    "target_key=3&" + 
                    "min_liveness=0.37298708414255066&" + 
                    "target_liveness=0.24036119714248005&" + 
                    "min_mode=0&" + 
                    "max_mode=1&" + 
                    "min_popularity=12&" + 
                    "max_popularity=10&" + 
                    "target_popularity=50&" + 
                    "min_speechiness=0.8491803885421456&" + 
                    "target_speechiness=0.15232783586534526&" + 
                    "min_tempo=3.7706721400759095E8&" + 
                    "target_tempo=9751779.453876628&" + 
                    "target_time_signature=357")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/v1/me/following
    */
    @Test(timeout = 60000)
    public void test_3_getOnFollowingReturns401() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/me/following?type=EVOMASTER")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", isEmptyOrNullString())
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(401))
                .body("'error'.'message'", containsString("Valid user authentication required"));
    }
    
    
    /**
    * Calls:
    * (403) GET:/v1/audio-analysis/{id}
    */
    @Test(timeout = 60000)
    public void test_4_getOnAudio_analysiReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/audio-analysis/fdz")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403));
    }
    
    
    /**
    * Calls:
    * (403) GET:/v1/audio-features/{id}
    * Using 1 example:
    *   (-) PATH: id -> 11dFghVXANMlKmJXsNCbNl
    */
    @Test(timeout = 60000)
    public void test_5_getOnAudio_featurReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/audio-features/11dFghVXANMlKmJXsNCbNl")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403));
    }
    
    
    /**
    * Calls:
    * (403) GET:/v1/browse/new-releases
    */
    @Test(timeout = 60000)
    public void test_6_getOnNew_releasesReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/browse/new-releases?offset=815")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Forbidden"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/v1/me/player
    */
    @Test(timeout = 60000)
    public void test_7_putOnPlayerReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .contentType("application/json")
                .put(baseUrlOfSut + "/v1/me/player")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Player command failed: Premium required"))
                .body("'error'.'reason'", containsString("PREMIUM_REQUIRED"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/v1/me/following
    */
    @Test(timeout = 60000)
    public void test_8_putOnFollowingReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"ids\" : [ \"OVnyTo7zA\", \"vqZB9apM\" ] " + 
                    " } ")
                .put(baseUrlOfSut + "/v1/me/following?" + 
                    "type=EVOMASTER&" + 
                    "ids=3t")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Forbidden"));
    }
    
    
    /**
    * Calls:
    * (403) DELETE:/v1/me/following
    */
    @Test(timeout = 60000)
    public void test_9_deleteOnFollowingReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .contentType("application/json")
                .body(" { } ")
                .delete(baseUrlOfSut + "/v1/me/following?" + 
                    "type=EVOMASTER&" + 
                    "ids=")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Forbidden"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v1/me/player
    */
    @Test(timeout = 60000)
    public void test_10_getOnPlayerReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/me/player?additional_types=N3ijXTsp")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(404))
                .body("'error'.'message'", containsString("Invalid username"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v1/recommendations/available-genre-seeds
    */
    @Test(timeout = 60000)
    public void test_11_getOnAvailable_genre_seedsReturns404() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/recommendations/available-genre-seeds")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (400) GET:/v1/playlists/{playlist_id}/images
    */
    @Test(timeout = 60000)
    public void test_12_getOnImagesReturns400() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/playlists/7/images")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(400))
                .body("'error'.'message'", containsString("Invalid base62 id"));
    }
    
    
    /**
    * Calls:
    * (401) PUT:/v1/playlists/{playlist_id}/images
    */
    @Test(timeout = 60000)
    public void test_13_putOnImagesReturns401() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .contentType("image/jpeg")
                .body("aHZqYWtKZ0dBck8=")
                .put(baseUrlOfSut + "/v1/playlists/hvjakJgGArO/images")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", isEmptyOrNullString())
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(401))
                .body("'error'.'message'", containsString("Valid user authentication required"));
    }
    
    
    /**
    * Calls:
    * (403) GET:/v1/me/player/queue
    */
    @Test(timeout = 60000)
    public void test_14_getOnQueueReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/me/player/queue")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Forbidden."));
    }
    
    
    /**
    * Calls:
    * (403) GET:/v1/me/player/recently-played
    */
    @Test(timeout = 60000)
    public void test_15_getOnRecently_playedReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/me/player/recently-played?" + 
                    "limit=43&" + 
                    "after=143")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Insufficient client scope"));
    }
    
    
    /**
    * Calls:
    * (403) GET:/v1/me/following/contains
    */
    @Test(timeout = 60000)
    public void test_16_getOnFollowingContainsWithQueryParamsReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/me/following/contains?" + 
                    "type=artist&" + 
                    "ids=wJ7SU")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Forbidden"));
    }
    
    
    /**
    * Calls:
    * (403) GET:/v1/browse/categories/{category_id}
    * Using 1 example:
    *   (-) PATH: category_id -> dinner
    */
    @Test(timeout = 60000)
    public void test_17_getOnCategoriReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/browse/categories/dinner")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Forbidden"));
    }
    
    
    /**
    * Calls:
    * (403) PUT:/v1/me/player/play
    */
    @Test(timeout = 60000)
    public void test_18_putOnPlayReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .contentType("application/json")
                .body(" { " + 
                    " \"offset\" : { " + 
                    " \"EM_tainted_map\" : \"_EM_14_XYZ_\" " + 
                    " }, " + 
                    " \"position_ms\" : { " + 
                    " \"EM_tainted_map\" : \"_EM_15_XYZ_\" " + 
                    " } " + 
                    " } ")
                .put(baseUrlOfSut + "/v1/me/player/play")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Player command failed: Premium required"))
                .body("'error'.'reason'", containsString("PREMIUM_REQUIRED"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v1/me/player/currently-playing
    */
    @Test(timeout = 60000)
    public void test_19_getOnCurrently_playingReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/me/player/currently-playing?additional_types=DJJy1eIQrF_1pKGu")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(404))
                .body("'error'.'message'", containsString("Invalid username"));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v1/me/player/devices
    */
    @Test(timeout = 60000)
    public void test_20_getOnDevicesReturns404() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/me/player/devices")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(404))
                .body("'error'.'message'", containsString("Invalid username"));
    }
    
    
    /**
    * Calls:
    * (411) POST:/v1/me/player/queue
    */
    @Test(timeout = 60000)
    public void test_21_postOnQueueReturns411() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .noContentType()
                .post(baseUrlOfSut + "/v1/me/player/queue?" + 
                    "uri=4O8NPQt&" + 
                    "device_id=aQVbeI_5Fn")
                .then()
                .statusCode(411)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (411) POST:/v1/me/player/previous
    */
    @Test(timeout = 60000)
    public void test_22_postOnPreviousReturns411() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .noContentType()
                .post(baseUrlOfSut + "/v1/me/player/previous?device_id=SDBKo")
                .then()
                .statusCode(411)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (411) POST:/v1/me/player/next
    */
    @Test(timeout = 60000)
    public void test_23_postOnNextReturns411() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .noContentType()
                .post(baseUrlOfSut + "/v1/me/player/next?device_id=p0sUHYZ")
                .then()
                .statusCode(411)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (411) PUT:/v1/me/player/shuffle
    */
    @Test(timeout = 60000)
    public void test_24_putOnShuffleReturns411() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .put(baseUrlOfSut + "/v1/me/player/shuffle?state=false")
                .then()
                .statusCode(411)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (411) PUT:/v1/me/player/volume
    */
    @Test(timeout = 60000)
    public void test_25_putOnVolumeReturns411() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .put(baseUrlOfSut + "/v1/me/player/volume?" + 
                    "volume_percent=822&" + 
                    "device_id=9gIQTnqeAiY")
                .then()
                .statusCode(411)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (411) PUT:/v1/me/player/repeat
    */
    @Test(timeout = 60000)
    public void test_26_putOnRepeatReturns411() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .put(baseUrlOfSut + "/v1/me/player/repeat?state=HeM")
                .then()
                .statusCode(411)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (411) PUT:/v1/me/player/seek
    */
    @Test(timeout = 60000)
    public void test_27_putOnSeekReturns411() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .put(baseUrlOfSut + "/v1/me/player/seek?position_ms=1000")
                .then()
                .statusCode(411)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (411) PUT:/v1/me/player/pause
    */
    @Test(timeout = 60000)
    public void test_28_putOnPauseReturns411() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .put(baseUrlOfSut + "/v1/me/player/pause")
                .then()
                .statusCode(411)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (403) GET:/v1/playlists/{playlist_id}/followers/contains
    * Using 1 example:
    *   (-) QUERY: ids -> jmperezperez
    */
    @Test(timeout = 60000)
    public void test_29_getOnFollowersContainsWithQueryParamReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/playlists/tGCMuery00RUZuvl/followers/contains?ids=jmperezperez")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Forbidden"));
    }
    
    
    /**
    * Calls:
    * (403) GET:/v1/browse/categories/{category_id}/playlists
    */
    @Test(timeout = 60000)
    public void test_30_getOnPlaylistsReturns403() throws Exception {
        
        given().accept("application/json")
                .header("Authorization", "Bearer BQDnwbTh8hCjwgAysEyHhXD80ThKtjZhNea2oqqdxEKWpX93B361XTezamHMwsqz2chwpwsEqALb1VgWh12N-wBO0DVRU2uAyRaaAsmRdoNKW6mq627xLGSsJo4MQvjEBUQgyR6NiubR") // Fixed Headers
                .get(baseUrlOfSut + "/v1/browse/categories/y2twNyFq/playlists?limit=4")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("application/json")
                .body("'error'.'status'", numberMatches(403))
                .body("'error'.'message'", containsString("Forbidden"));
    }


}
