#!/usr/bin/env python

# LICENSE DISCLAIMER
# This file has been generated by EvoMaster.
# The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
# This generated software (i.e., the test suite in this file) can be freely used, modified, 
# and distributed as you see fit without any restrictions.
import json
import unittest
import requests
import time
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *
EM_HTTP_TIMEOUT_S = 30.0


#  This file was automatically generated by EvoMaster on 2026-08-12T20:04:53.281659153-03:00[America/Argentina/Buenos_Aires]
#  
#  The generated test suite contains 8 tests
#  
#  Covered targets: 21
#  
#  Used time: 0h 7m 33s
#  
#  Needed budget for current results: 94%
#  
#  This file contains test cases that represent failed calls, but not indicative of faults.
#  
class EvoMaster_others_Test(unittest.TestCase):

    
    baseUrlOfSut = "https://api-m.sandbox.paypal.com"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (404) OPTIONS:/v2/checkout/orders
    @timeout_decorator.timeout(60)
    def test_0_options_on_orders_returns_404(self):
        
        headers = {}
        headers["Authorization"] = "Bearer A21AAIKqlKxpr13443_ZhqrOcjrSwBNHdVkmvC3dGLEfixMcuDc9wb8NHBbPTKBsNLjB9GpgD30Cd2UlPWlbs5W_y_lofvznA"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v2/checkout/orders",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert res_0.text == ''
    
    
    # Calls:
    # (404) OPTIONS:/v2/checkout/orders/{id}
    @timeout_decorator.timeout(60)
    def test_1_options_on_order_returns_404(self):
        
        headers = {}
        headers["Authorization"] = "Bearer A21AAIKqlKxpr13443_ZhqrOcjrSwBNHdVkmvC3dGLEfixMcuDc9wb8NHBbPTKBsNLjB9GpgD30Cd2UlPWlbs5W_y_lofvznA"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v2/checkout/orders/KG3",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert res_0.text == ''
    
    
    # Calls:
    # (404) OPTIONS:/v2/checkout/orders/order-update-callback
    @timeout_decorator.timeout(60)
    def test_2_options_on_order_update_callback_returns_404(self):
        
        headers = {}
        headers["Authorization"] = "Bearer A21AAIKqlKxpr13443_ZhqrOcjrSwBNHdVkmvC3dGLEfixMcuDc9wb8NHBbPTKBsNLjB9GpgD30Cd2UlPWlbs5W_y_lofvznA"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v2/checkout/orders/order-update-callback",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert res_0.text == ''
    
    
    # Calls:
    # (404) OPTIONS:/v2/checkout/orders/{id}/confirm-payment-source
    @timeout_decorator.timeout(60)
    def test_3_options_on_confirm_payment_source_returns_404(self):
        
        headers = {}
        headers["Authorization"] = "Bearer A21AAIKqlKxpr13443_ZhqrOcjrSwBNHdVkmvC3dGLEfixMcuDc9wb8NHBbPTKBsNLjB9GpgD30Cd2UlPWlbs5W_y_lofvznA"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v2/checkout/orders/L/confirm-payment-source",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert res_0.text == ''
    
    
    # Calls:
    # (404) OPTIONS:/v2/checkout/orders/{id}/authorize
    @timeout_decorator.timeout(60)
    def test_4_options_on_authorize_returns_404(self):
        
        headers = {}
        headers["Authorization"] = "Bearer A21AAIKqlKxpr13443_ZhqrOcjrSwBNHdVkmvC3dGLEfixMcuDc9wb8NHBbPTKBsNLjB9GpgD30Cd2UlPWlbs5W_y_lofvznA"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v2/checkout/orders/V/authorize",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert res_0.text == ''
    
    
    # Calls:
    # (404) OPTIONS:/v2/checkout/orders/{id}/capture
    @timeout_decorator.timeout(60)
    def test_5_options_on_capture_returns_404(self):
        
        headers = {}
        headers["Authorization"] = "Bearer A21AAIKqlKxpr13443_ZhqrOcjrSwBNHdVkmvC3dGLEfixMcuDc9wb8NHBbPTKBsNLjB9GpgD30Cd2UlPWlbs5W_y_lofvznA"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v2/checkout/orders/2/capture",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert res_0.text == ''
    
    
    # Calls:
    # (404) OPTIONS:/v2/checkout/orders/{id}/track
    # Using 1 example:
    #   (orders_track_create_complete_request) PATH: id -> 5O190127TN364715T
    @timeout_decorator.timeout(60)
    def test_6_options_on_track_returns_404(self):
        
        headers = {}
        headers["Authorization"] = "Bearer A21AAIKqlKxpr13443_ZhqrOcjrSwBNHdVkmvC3dGLEfixMcuDc9wb8NHBbPTKBsNLjB9GpgD30Cd2UlPWlbs5W_y_lofvznA"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v2/checkout/orders/5O190127TN364715T/track",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert res_0.text == ''
    
    
    # Calls:
    # (404) OPTIONS:/v2/checkout/orders/{id}/trackers/{tracker_id}
    # Using 1 example:
    #   (example) PATH: tracker_id -> 8MC585209K746392H443844607820
    @timeout_decorator.timeout(60)
    def test_7_options_on_tracker_returns_404(self):
        
        headers = {}
        headers["Authorization"] = "Bearer A21AAIKqlKxpr13443_ZhqrOcjrSwBNHdVkmvC3dGLEfixMcuDc9wb8NHBbPTKBsNLjB9GpgD30Cd2UlPWlbs5W_y_lofvznA"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v2/checkout/orders/7/trackers/8MC585209K746392H443844607820",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 404
        assert res_0.text == ''


if __name__ == '__main__':
    unittest.main()
