#!/usr/bin/env python

# LICENSE DISCLAIMER
# This file has been generated by EvoMaster.
# The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
# This generated software (i.e., the test suite in this file) can be freely used, modified, 
# and distributed as you see fit without any restrictions.
import json
import unittest
import requests
import time
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *
EM_HTTP_TIMEOUT_S = 30.0


#  This file was automatically generated by EvoMaster on 2026-08-12T19:55:06.169420103-03:00[America/Argentina/Buenos_Aires]
#  
#  The generated test suite contains 11 tests
#  
#  Covered targets: 44
#  
#  Used time: 0h 10m 36s
#  
#  Needed budget for current results: 100%
#  
#  This file contains test cases that represent successful calls.
#  
class EvoMaster_successes_Test(unittest.TestCase):

    
    baseUrlOfSut = "https://api.twilio.com"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (200) OPTIONS:/2010-04-01/Accounts.json
    @timeout_decorator.timeout(60)
    def test_0_options_on_Accounts_json_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/2010-04-01/Accounts.json",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert res_0.text == ''
    
    
    # Calls:
    # (200) OPTIONS:/2010-04-01/Accounts/{Sid}.json
    @timeout_decorator.timeout(60)
    def test_1_options_on_Account_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/2010-04-01/Accounts/AC3da03b03db28AC82fFC6d5eCdCf8658F.json",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert res_0.text == ''
    
    
    # Calls:
    # (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Addresses.json
    @timeout_decorator.timeout(60)
    def test_2_options_on_Addresses_json_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/2010-04-01/Accounts/ACEeBEE8dC6c5d885DEeeD63Bb7cb1bCCE/Addresses.json",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert res_0.text == ''
    
    
    # Calls:
    # (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Applications.json
    @timeout_decorator.timeout(60)
    def test_3_options_on_Applications_json_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/2010-04-01/Accounts/ACa8E475Fc05Bfa1Cd235A9ea785d2b2B9/Applications.json",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert res_0.text == ''
    
    
    # Calls:
    # (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AuthorizedConnectApps.json
    @timeout_decorator.timeout(60)
    def test_4_options_on_AuthorizedConnectApps_json_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/2010-04-01/Accounts/AC6b1Ca95CCDDe4a2378cfF7c32BeBfDc8/AuthorizedConnectApps.json",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert res_0.text == ''
    
    
    # Calls:
    # (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers.json
    @timeout_decorator.timeout(60)
    def test_5_options_on_AvailablePhoneNumbers_json_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/2010-04-01/Accounts/AC9Adb2cEb105E9C5C83fEF29fFB183dD4/AvailablePhoneNumbers.json",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert res_0.text == ''
    
    
    # Calls:
    # (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Addresses/{Sid}.json
    @timeout_decorator.timeout(60)
    def test_6_options_on_Address_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/2010-04-01/Accounts/AC4B2cD1fbEbA9FE2AEAbFBE645B77aAEE/Addresses/ADFA61AE31EdD2d66Ec5D07Fb3655dCEDF.json",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert res_0.text == ''
    
    
    # Calls:
    # (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Applications/{Sid}.json
    @timeout_decorator.timeout(60)
    def test_7_options_on_Applicat_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/2010-04-01/Accounts/ACd4E5aeFBAbDe5e8B544b3f5cCF25c3E4/Applications/APDeD3aE20FBc0c366Fe1d8B81B9dE2650.json",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert res_0.text == ''
    
    
    # Calls:
    # (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AuthorizedConnectApps/{ConnectAppSid}.json
    @timeout_decorator.timeout(60)
    def test_8_options_on_AuthorizedConnectApp_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/2010-04-01/Accounts/ACDbeF3D511c0DD6f61425cbAcD1e3adD3/AuthorizedConnectApps/CND2a6bb1b17c87A3fbbbAF9fAD3a1D0bf.json",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert res_0.text == ''
    
    
    # Calls:
    # (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}.json
    @timeout_decorator.timeout(60)
    def test_9_options_on_AvailablePhoneNumb_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/2010-04-01/Accounts/ACbCdce8Fac61f72c0e0dEDAAAfD5CfBf9/AvailablePhoneNumbers/G3dgyN.json",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert res_0.text == ''
    
    
    # Calls:
    # (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/AvailablePhoneNumbers/{CountryCode}/Local.json
    @timeout_decorator.timeout(60)
    def test_10_options_on_Local_json_returns_200(self):
        
        headers = {}
        headers["Authorization"] = "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/2010-04-01/Accounts/ACF402BbC9fDBb80B1AE15A5Ae1F6Cbc57/AvailablePhoneNumbers/eSJpSWA4P2JxtpB/Local.json",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert res_0.text == ''


if __name__ == '__main__':
    unittest.main()
