openapi: 3.0.0
info:
  title: Simple DTO API
  version: 1.0.0
servers:
  - url: https://localhost:5000
paths:
  /object:
    post:
      summary: Receives a Person object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        "200":
          description: Successfully received object
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/components/schemas/Person"
  /array:
    post:
      summary: Receives an array of Person objects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Person"
      responses:
        "200":
          description: Successfully received array
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Person"
  /string:
    post:
      summary: Receives a string
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: Successfully received string
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: string
  # /enum-examples:
  #   post:
  #     summary: Submit an object using examples
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/EnumExample'
  #     responses:
  #       '200':
  #         description: OK
components:
  schemas:
    Person:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        address:
          $ref: "#/components/schemas/Address"
      required:
        - name
        - age
        - address
    Address:
      type: object
      properties:
        street:
          type: string
        country:
          type: string
        voted:
          type: boolean
      required:
        - street
        - country
    # EnumExample:
    #   type: object
    #   properties:
    #     textValue:
    #       type: string
    #       example: "hello world"
    #     flagValue:
    #       type: boolean
    #       example: true
    #     countValue:
    #       type: integer
    #       example: 33
    #     longValue:
    #       type: integer
    #       format: int64
    #       example: 10
    #     scoreValue:
    #       type: number
    #       format: float
    #       example: 3.14
    #     listValue:
    #       type: array
    #       items:
    #         type: string
    #       example: [ "s1", "s2", "s3" ]
    #   required:
    #     - textValue
    #     - flagValue
    #     - longValue
    #     - countValue
    #     - scoreValue
    #     - listValue
