/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import  io.restassured.config.HttpClientConfig;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import  io.restassured.config.EncoderConfig;
import  io.restassured.http.ContentType;
import  org.hamcrest.Matchers;
import static org.hamcrest.Matchers.*;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-07-27T21:16:10.714454342-03:00[America/Argentina/Buenos_Aires]
 * <br>
*  The generated test suite contains 41 tests
 * <br>
*  Covered targets: 352
 * <br>
*  Used time: 0h 4m 18s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that are likely to indicate faults.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_faults_Test {

    
    private static String baseUrlOfSut = "https://api.twilio.com";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .httpClient(HttpClientConfig.httpClientConfig()
                .setParam("http.socket.timeout", 30000)
                .setParam("http.connection.timeout", 30000))
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .encoderConfig(EncoderConfig.encoderConfig().encodeContentTypeAs("application/octet-stream", ContentType.TEXT));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Transcriptions.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_0_getOnTranscriptions_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Transcriptions.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/AC9ECf074fDcdaae2915d12E89Ecf2a1E6/Transcriptions.json?PageToken=OKp1aN")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/Tokens.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_1_postOnTokens_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Tokens.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/AC13B6D19E7377a1eDAb67ACd36a9DAfd4/Tokens.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Usage/Triggers.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_2_getOnTriggers_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Triggers.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/AC5aD6Bc8aefA9b630E02F0FBcBa9CeFAe/Usage/Triggers.json?" + 
                    "UsageCategory=c5asCY&" + 
                    "PageSize=882&" + 
                    "PageToken=")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Usage/Records.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_3_getOnRecords_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Records.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/ACf9d2513ae8e55E32201ecdDB9BaAC9F4/Usage/Records.json?" + 
                    "EndDate=2081-13-20&" + 
                    "IncludeSubaccounts=true")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Transcriptions/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_4_getOnTranscriptReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Transcriptions/{Sid}.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/ACF2A579d3548513e74Fa9be4aDefF5C4C/Transcriptions/TRdede3e376a063C8b9AeF5BbA6866F68e.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_5_getOnIpAccessControlLists_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/ACe2DaCBFF4Cf29C0ee5bEAFbbf2417C31/SIP/IpAccessControlLists.json?PageSize=222")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/Usage/Triggers.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_6_postOnTriggers_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Triggers.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/AC6AcAC5273aEe42b800dA5D218A9D1ae6/Usage/Triggers.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_7_postOnIpAccessControlLists_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("FriendlyName=YkGBaUsByVh")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/ACBC00CE5FbFBaAC319aaC0dC60f824e6b/SIP/IpAccessControlLists.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/2010-04-01/Accounts/{AccountSid}/Transcriptions/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_8_deleteOnTranscriptReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Transcriptions/{Sid}.json'.
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .delete(baseUrlOfSut + "/2010-04-01/Accounts/ACCc9bdF7975Bfe653e84Cabfe3b4EA375/Transcriptions/TR9d4F9eCDb4be87bc2a26EB6Fdd3bCb5f.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Usage/Triggers/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_9_getOnTriggerReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Triggers/{Sid}.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/ACFeffDa85B35AAE8E7AE87c8F960befe1/Usage/Triggers/UTC97Dcf71CdeeeC8eC9eb5F7bEDa23dC6.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Usage/Records/Yesterday.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_10_getOnYesterday_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Records/Yesterday.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/AC8A40ACdFc0CfddcD48aaF643d2fBa98D/Usage/Records/Yesterday.json?" + 
                    "Category=8Hf0H&" + 
                    "StartDate=1922-02-14&" + 
                    "Page=206&" + 
                    "PageToken=vSP6tg6lhPJOeIu")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Usage/Records/Yearly.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_11_getOnYearly_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Records/Yearly.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/AC5cBDb88Db8572Ac5Fd6254FE6B28FfDA/Usage/Records/Yearly.json?" + 
                    "EndDate=2011-01-19&" + 
                    "Page=894")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Usage/Records/Today.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_12_getOnToday_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Records/Today.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/ACD5C92381ED03F9DcAd1a12Ef1f0AE90C/Usage/Records/Today.json?" + 
                    "StartDate=1915-04-26&" + 
                    "IncludeSubaccounts=true&" + 
                    "PageSize=978")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Usage/Records/ThisMonth.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_13_getOnThisMonth_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Records/ThisMonth.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/AC1cAEAF8ee3Ef6844A2EB44a7ebbAC9BB/Usage/Records/ThisMonth.json?" + 
                    "Category=Eg9dCWLrK&" + 
                    "StartDate=1918-00-15&" + 
                    "PageSize=565&" + 
                    "Page=676&" + 
                    "PageToken=9GE9O0D")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Usage/Records/Monthly.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_14_getOnMonthly_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Records/Monthly.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/ACaBC48ca3d5Df9d45Fa6A904eaF98fEb8/Usage/Records/Monthly.json?" + 
                    "StartDate=2074-03-01&" + 
                    "EndDate=1980-01-12&" + 
                    "Page=158&" + 
                    "PageToken=O2vMz5")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Usage/Records/LastMonth.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_15_getOnLastMonth_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Records/LastMonth.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/ACd0A79BFFcCbcee423A4F4b54eDf9D0ee/Usage/Records/LastMonth.json?" + 
                    "EndDate=1980-01-32&" + 
                    "PageSize=124&" + 
                    "Page=168&" + 
                    "PageToken=REGDmNyBiff_")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Usage/Records/Daily.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_16_getOnDaily_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Records/Daily.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/AC0Bc9A3Db916471c47f9173AA1948bdB5/Usage/Records/Daily.json?" + 
                    "StartDate=2064-00-29&" + 
                    "EndDate=2041-07-05&" + 
                    "IncludeSubaccounts=true&" + 
                    "PageSize=719&" + 
                    "Page=277")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/Usage/Records/AllTime.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_17_getOnAllTime_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Records/AllTime.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/ACe8b1C76aAE3AFAeba7E2015Ae2228cbD/Usage/Records/AllTime.json?" + 
                    "Category=PAfO_UHrEw8oy&" + 
                    "EndDate=1975-06-27&" + 
                    "PageToken=PzhGLmzatPg5oN5")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_18_getOnIpAccessControlListReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{Sid}.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/AC1aFEbfD4e5b1dDdE9D3920c2bAa277fA/SIP/IpAccessControlLists/AL3B0026F37Ba2fa7B1EcCfACCa7c33B03.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/UserDefinedMessageSubscriptions.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_19_postOnUserDefinedMessageSubscriptions_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/UserDefinedMessageSubscriptions.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/ACbaB9eaCEcAdacE6E7C10Ab111ff4118a/Calls/CAfEAE5b94cb00B7c6bb1adAbCdd9ffcFE/UserDefinedMessageSubscriptions.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/UserDefinedMessages.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_20_postOnUserDefinedMessages_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/UserDefinedMessages.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/ACcEBDf990C599B44ABAeDFE32a54e4a5a/Calls/CAD318C2CEe11FC3DF84F83AAf4712d8Ea/UserDefinedMessages.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/Usage/Triggers/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_21_postOnTriggerReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Triggers/{Sid}.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/ACe524EE212389fdEefF15D9cb8FbB482E/Usage/Triggers/UT1DE4Af77D7b2F0FcEC12ea92Ca59Df24.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Streams.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_22_postOnStreams_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Streams.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/AC34f4421bB40A4085C5BD4560D005E527/Calls/CA10Acc97F9Ac41f9fD4B79ee23cDcdf9d/Streams.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Siprec.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_23_postOnSiprec_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Siprec.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/AC8995a7d8b4EcCa9E1FEE348CAFFcC1d6/Calls/CA9cd796f61Aa09697Af2ee876bD6B4C3F/Siprec.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_24_postOnIpAccessControlListReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{Sid}.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("FriendlyName=dL0GLIAsTZbxgwt")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/AC1f172b0DE31A16cCeEf2b4fd1aDBEe8a/SIP/IpAccessControlLists/ALbFfFe1E97bBE3eCBf8BB898c2f0F5F4A.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_25_postOnDomainReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{Sid}.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/ACCd36186EAE6Eed2fe3d84c628dEe7Edf/SIP/Domains/SDD7b3c132caCb11Ed8BF9aB3e9407CDEe.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/2010-04-01/Accounts/{AccountSid}/Usage/Triggers/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_26_deleteOnTriggerReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Usage/Triggers/{Sid}.json'.
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .delete(baseUrlOfSut + "/2010-04-01/Accounts/AC4433afFaDb2d05Af478921B24Bf2E1bb/Usage/Triggers/UT8bc4045E90ce290da1466481bd1dFFD2.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_27_deleteOnIpAccessControlListReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{Sid}.json'.
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .delete(baseUrlOfSut + "/2010-04-01/Accounts/AC5beBeb9d2883ad8ED3F743A6Df603aa5/SIP/IpAccessControlLists/AL85F286b5bE5468c36BffE7f7b2da05ab.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_28_deleteOnDomainReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{Sid}.json'.
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .delete(baseUrlOfSut + "/2010-04-01/Accounts/ACff5385AfBF93D10ee7A0AA35a90f4FBC/SIP/Domains/SD40bf28DC404dEBaA09a3AAfc5cCcE953.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_29_getOnIpAddresses_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/AC1BFbdbcb18cD9DC8E007FCE3DFcc21f1/SIP/IpAccessControlLists/AL824dAB57Ef25e176c0E03738ccB9d40e/IpAddresses.json?PageToken=ZnkyinfKH9")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_30_getOnIpAccessControlListMappings_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/ACDee423851b4dc1eCF425905d632C0Eb1/SIP/Domains/SD6B9aAFb9eD2fCbEfCfD7f2a10398eE1f/IpAccessControlListMappings.json?" + 
                    "PageSize=117&" + 
                    "PageToken=PE")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Streams/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_31_postOnStreamReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Streams/{Sid}.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/ACEe82AE897a8d048Bb3eCEEcC01a5bffe/Calls/CA0c81879bc0e6CDCFb7bdfd5bc11Ae9aF/Streams/GdzNdBeVIyj.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Siprec/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_32_postOnSiprecReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/Siprec/{Sid}.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/ACEfB60c8eBc5D6e6692446432dfde9376/Calls/CAaaA69928A518f70CAA1d2E91DAbBB6AC/Siprec/TERrAg_pg.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_33_postOnIpAddresses_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/ACcee1E1Df8ED37bDfbfa26C7AC7BA14AC/SIP/IpAccessControlLists/ALDF7eeebEb618DFE7B7CAEf8C4d712B2A/IpAddresses.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings.json
    * Found 1 potential fault of type-code 101
    * Using 1 example:
    *   (create) BODY -> {"IpAccessControlListSid":"ALaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}
    */
    @Test(timeout = 60000)
    public void test_34_postOnIpAccessControlListMappings_jsonReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("IpAccessControlListSid=ALaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/ACfD5AF956a0149e1b59aeFdA93771aDdB/SIP/Domains/SD955AD66EfC3C1f1a46fbe3ACC04b9B21/IpAccessControlListMappings.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/UserDefinedMessageSubscriptions/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_35_deleteOnUserDefinedMessageSubscriptReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/Calls/{CallSid}/UserDefinedMessageSubscriptions/{Sid}.json'.
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .delete(baseUrlOfSut + "/2010-04-01/Accounts/AC3C737a62dfBDEdc0274e247cD7EdBf4F/Calls/CA2bDBa4aE188ddAB9543539c40F54FbbE/UserDefinedMessageSubscriptions/ZY5451C19e959a9DdEdc1Dddab5C02Ace7.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_36_getOnIpAddressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{Sid}.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/ACdcEfE1f21Fb0C8a0dCAe7EE22181AB7b/SIP/IpAccessControlLists/ALddc6Ad926f3a3ce390c7Ac692a5efe9A/IpAddresses/IP7519dB1DE6Fa8F53C5F4Ee26a5dfD7f3.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) GET:/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_37_getOnIpAccessControlListMapReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings/{Sid}.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .get(baseUrlOfSut + "/2010-04-01/Accounts/AC5c927F1Cf9D4db20cc5B3Fc86D0e2a7C/SIP/Domains/SD2200dFff28cE76BDd3eb6d2d0DC441bd/IpAccessControlListMappings/ALDcCAaCF6a5aD58d8b55cBF2F97cbf16B.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) POST:/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_38_postOnIpAddressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{Sid}.json'.
        given().accept("application/json")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/2010-04-01/Accounts/ACFb4cFDAcDBf1F4C35A64fBB64aE4e101/SIP/IpAccessControlLists/ALdEd3278Ad7feaf14999BEDc7eDA2ccFD/IpAddresses/IPf86a6b0115efD53c93cE9fbD9DEBbC1f.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_39_deleteOnIpAddressReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/IpAccessControlLists/{IpAccessControlListSid}/IpAddresses/{Sid}.json'.
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .delete(baseUrlOfSut + "/2010-04-01/Accounts/ACCCadd6Aa2C00c1d5e2eE5Cbdfb4b1aF4/SIP/IpAccessControlLists/ALC0A67CfaE90C0EFcE949Fbd5b2DfdBA4/IpAddresses/IP18803AA379280CADB0a5FfAd38ea7Dea.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }
    
    
    /**
    * Calls:
    * (401) DELETE:/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings/{Sid}.json
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_40_deleteOnIpAccessControlListMapReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 401 not defined for path '/2010-04-01/Accounts/{AccountSid}/SIP/Domains/{DomainSid}/IpAccessControlListMappings/{Sid}.json'.
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .delete(baseUrlOfSut + "/2010-04-01/Accounts/AC2220BC731dd0be2c26f71Be7bDa0eD1c/SIP/Domains/SD3EbDddE8079AcE51e7AD0BA37882e6A6/IpAccessControlListMappings/AL485Ce55Ab8576877b8eBD3E7beF3E173.json")
                .then()
                .statusCode(401)
                .assertThat()
                .header("www-authenticate", "Basic realm=\"Twilio API\"")
                .contentType("application/json")
                .body("'code'", numberMatches(20003))
                .body("'message'", containsString("Authenticate"))
                .body("'more_info'", containsString("https://www.twilio.com/docs/errors/20003"))
                .body("'status'", numberMatches(401));
    }


}
