/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  java.math.BigDecimal;
import  java.math.BigInteger;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import  io.restassured.config.HttpClientConfig;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import  io.restassured.config.EncoderConfig;
import  io.restassured.http.ContentType;
import  org.hamcrest.Matchers;
import static org.hamcrest.Matchers.*;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-07-27T21:16:10.777838814-03:00[America/Argentina/Buenos_Aires]
 * <br>
*  The generated test suite contains 5 tests
 * <br>
*  Covered targets: 20
 * <br>
*  Used time: 0h 4m 18s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent successful calls.
 * <br>
*  ******************************** IMPORTANT ********************************
*  * If you are planning to modify these test cases manually, you might
*  * want to consider using the '--dtoForRequestPayload true' option to
*  * generate statically typed DTOs instead of payloads defined with strings.
*  ***************************************************************************
 * <br>
*/
public class EvoMaster_successes_Test {

    
    private static String baseUrlOfSut = "https://api.twilio.com";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .httpClient(HttpClientConfig.httpClientConfig()
                .setParam("http.socket.timeout", 30000)
                .setParam("http.connection.timeout", 30000))
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false))
            .encoderConfig(EncoderConfig.encoderConfig().encodeContentTypeAs("application/octet-stream", ContentType.TEXT));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts.json
    */
    @Test(timeout = 60000)
    public void test_0_optionsOnAccounts_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{Sid}.json
    */
    @Test(timeout = 60000)
    public void test_1_optionsOnAccountReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACb7cBEE7de4e4BeF22410ec415Ed3afee.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Addresses.json
    */
    @Test(timeout = 60000)
    public void test_2_optionsOnAddresses_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACA22a3Bef7F70B64B5dDAc0bABBF3218E/Addresses.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Applications.json
    */
    @Test(timeout = 60000)
    public void test_3_optionsOnApplications_jsonReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACbfF5f201b2fd67aeb7B9f16Cdbd4BEcF/Applications.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) OPTIONS:/2010-04-01/Accounts/{AccountSid}/Addresses/{Sid}.json
    */
    @Test(timeout = 60000)
    public void test_4_optionsOnAddressReturns200() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "Basic QUM3ZTg4YjA2MjllNDhjYzdmOGE4YzVhYjU2YzBiMTM1OTo1OTc1YTMwMzZhYTA3MzRmYzNkNzc5MTZkZjY3MDIyYw") // Fixed Headers
                .options(baseUrlOfSut + "/2010-04-01/Accounts/ACd4ef8bA1448B1F665Bb68EA867b195C3/Addresses/AD1C631b31f0609AaFeAAa3E730c31c2f5.json")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
