#!/usr/bin/env python

# LICENSE DISCLAIMER
# This file has been generated by EvoMaster.
# The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
# This generated software (i.e., the test suite in this file) can be freely used, modified, 
# and distributed as you see fit without any restrictions.
import json
import unittest
import requests
import time
import os
if os.name == 'nt':
    class timeout_decorator:
        @staticmethod
        def timeout(*args, **kwargs):
            return lambda f: f # return a no-op decorator
else:
    import timeout_decorator
from em_test_utils import *
EM_HTTP_TIMEOUT_S = 30.0


#  This file was automatically generated by EvoMaster on 2026-08-12T20:36:33.296783299-03:00[America/Argentina/Buenos_Aires]
#  
#  The generated test suite contains 14 tests
#  
#  Covered targets: 68
#  
#  Used time: 0h 10m 26s
#  
#  Needed budget for current results: 100%
#  
#  This file contains test cases that represent successful calls.
#  
class EvoMaster_successes_Test(unittest.TestCase):

    
    baseUrlOfSut = "https://api.spotify.com"
    
    
    
    
    
    
    
    
    
    
    # Calls:
    # (204) OPTIONS:/v1/albums
    @timeout_decorator.timeout(60)
    def test_0_options_on_v1_albums_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/albums",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (204) OPTIONS:/v1/artists
    @timeout_decorator.timeout(60)
    def test_1_options_on_artists_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/artists",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (204) OPTIONS:/v1/shows
    @timeout_decorator.timeout(60)
    def test_2_options_on_shows_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/shows",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (204) OPTIONS:/v1/episodes
    @timeout_decorator.timeout(60)
    def test_3_options_on_v1_episodes_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/episodes",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (200) GET:/v1/artists/{id}
    # Using 1 example:
    #   (-) PATH: id -> 0TnOYISbd1XYRBk9myaseg
    @timeout_decorator.timeout(60)
    def test_4_get_on_artist_returns_object(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "application/json"
        res_0 = requests \
                .get(self.baseUrlOfSut + "/v1/artists/0TnOYISbd1XYRBk9myaseg",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 200
        assert "application/json" in res_0.headers["content-type"]
        assert res_0.json()["external_urls"]["spotify"] == "https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg"
        assert res_0.json()["href"] == "https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg"
        assert len(res_0.json()["images"]) == 3
        assert res_0.json()["images"][0]["url"] == "https://i.scdn.co/image/ab6761610000e5eb8d8ac7290d0fe2d12fb6e4d9"
        assert res_0.json()["images"][0]["height"] == 640
        assert res_0.json()["images"][0]["width"] == 640
        assert res_0.json()["images"][1]["url"] == "https://i.scdn.co/image/ab676161000051748d8ac7290d0fe2d12fb6e4d9"
        assert res_0.json()["images"][1]["height"] == 320
        assert res_0.json()["images"][1]["width"] == 320
        assert res_0.json()["images"][2]["url"] == "https://i.scdn.co/image/ab6761610000f1788d8ac7290d0fe2d12fb6e4d9"
        assert res_0.json()["images"][2]["height"] == 160
        assert res_0.json()["images"][2]["width"] == 160
        assert res_0.json()["name"] == "Pitbull"
        assert res_0.json()["type"] == "artist"
        assert res_0.json()["uri"] == "spotify:artist:0TnOYISbd1XYRBk9myaseg"
    
    
    # Calls:
    # (204) OPTIONS:/v1/albums/{id}
    # Using 1 example:
    #   (-) PATH: id -> 4aawyAB9vmqN3uQ7FjRGTy
    @timeout_decorator.timeout(60)
    def test_5_options_on_album_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/albums/4aawyAB9vmqN3uQ7FjRGTy",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (204) OPTIONS:/v1/artists/{id}
    @timeout_decorator.timeout(60)
    def test_6_options_on_artist_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/artists/0TnOYISbd1XYRBk9myaseg",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (204) OPTIONS:/v1/shows/{id}
    @timeout_decorator.timeout(60)
    def test_7_options_on_show_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/shows/fZw",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (204) OPTIONS:/v1/episodes/{id}
    @timeout_decorator.timeout(60)
    def test_8_options_on_episod_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/episodes/pFbR",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (204) OPTIONS:/v1/albums/{id}/tracks
    # Using 1 example:
    #   (-) PATH: id -> 4aawyAB9vmqN3uQ7FjRGTy
    @timeout_decorator.timeout(60)
    def test_9_options_on_tracks_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/albums/4aawyAB9vmqN3uQ7FjRGTy/tracks",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (204) OPTIONS:/v1/artists/{id}/albums
    @timeout_decorator.timeout(60)
    def test_10_options_on_artist_albums_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/artists/LR8rhQ/albums",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (204) OPTIONS:/v1/artists/{id}/top-tracks
    @timeout_decorator.timeout(60)
    def test_11_options_on_top_tracks_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/artists/TU/top-tracks",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (204) OPTIONS:/v1/artists/{id}/related-artists
    # Using 1 example:
    #   (-) PATH: id -> 0TnOYISbd1XYRBk9myaseg
    @timeout_decorator.timeout(60)
    def test_12_options_on_related_artists_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/artists/0TnOYISbd1XYRBk9myaseg/related-artists",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''
    
    
    # Calls:
    # (204) OPTIONS:/v1/shows/{id}/episodes
    @timeout_decorator.timeout(60)
    def test_13_options_on_show_episodes_returns_204(self):
        
        headers = {}
        headers["Authorization"] = "Bearer BQBF2pebO5hmM27W4U5COVGQlJp22TSQmLNMKQedjAYN1JazdDw3qeS-iZLUXsjwAhV4zfNcRkx-TmGkyGk7zuQknZzbxyE7_BTplFXslkYgnRYrh0aejjTtPVFckpwYnHGfU5b8wm84"
        headers['Accept'] = "*/*"
        res_0 = requests \
                .options(self.baseUrlOfSut + "/v1/shows/AwD/episodes",
                    headers=headers, timeout=EM_HTTP_TIMEOUT_S, verify=False)
        
        assert res_0.status_code == 204
        # assert "GET, HEAD, OPTIONS" in res_0.headers["allow"]
        assert res_0.text == ''


if __name__ == '__main__':
    unittest.main()
